"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { SoftwareLogistics } from "./v31-software";

export type SystemControlArea = "telemetry" | "network" | "wifi" | "bluetooth" | "audio" | "displays" | "software" | "processes" | "storage" | "modules" | "media";

type WifiNetwork={id:string;name:string;signal:number;security:string;connected:boolean;saved:boolean};
type BluetoothDevice={id:string;name:string;paired:boolean;connected:boolean;trusted:boolean};
type Connectivity={ok:boolean;platform:string;wifi:{available:boolean;enabled:boolean;active:string;interface:string;networks:WifiNetwork[];control:boolean;reason:string};bluetooth:{available:boolean;enabled:boolean;devices:BluetoothDevice[];control:boolean;reason:string}};
type Display={id:string;name:string;enabled:boolean;primary:boolean;geometry:string;source?:string};
type AudioDevice={id:string;name:string;default:boolean;kind:"output"|"input"};
type Stream={id:string;name:string;volume:number;group?:string;muted?:boolean};
type Process={pid:number;name:string;cpu:number;memory:number;user:string;state:string;protected:boolean};
type Drive={id:string;name:string;size:number;type:string;filesystem:string;mountpoints:string[];mounted:boolean;removable:boolean};
type Software={ok:boolean;manager:string;available:boolean;updates:{name:string;current:string;available:string}[];count:number;command:string;detail:string};
type AppEntry={id:string;name:string;comment:string};
type ModuleEntry={id:string;name:string;version:string;description:string};
type Meter=[string,number,string];
type MemoryModule={bank:string;capacity:number;speed?:number;manufacturer?:string;part?:string};
type GraphicsAdapter={name:string;vendor?:string;driver?:string;usage?:number;temperature?:number|null;memoryTotal?:number;memoryUsed?:number;resolution?:string};
type SystemDetails={cpu?:{logical:number;load:number[];cores:{name:string;usage:number}[]};memory?:{total:number;used:number;available:number;percent:number;swapTotal:number;swapUsed:number;modules?:MemoryModule[]};graphics?:GraphicsAdapter[];storage?:Drive[];kernel?:string};
type Sensor={id:string;name:string;kind:string;value:string;detail?:string;status:string};

const emptyConnectivity:Connectivity={ok:false,platform:"",wifi:{available:false,enabled:false,active:"",interface:"",networks:[],control:false,reason:"LOCAL CORE LINK REQUIRED"},bluetooth:{available:false,enabled:false,devices:[],control:false,reason:"LOCAL CORE LINK REQUIRED"}};
const areas:[SystemControlArea,string,string][]=[
  ["telemetry","TLM","TELEMETRY"],
  ["network","NET","NETWORK"],["wifi","WIFI","WI-FI"],["bluetooth","BT","BLUETOOTH"],["audio","AUD","AUDIO"],["displays","DSP","DISPLAYS"],
  ["software","SFT","SOFTWARE"],["processes","SYS","PROCESSES"],["storage","DRV","STORAGE"],["modules","MOD","MODULES"],["media","MED","MEDIA"],
];
const bytes=(value:number)=>value>=1099511627776?(value/1099511627776).toFixed(1)+" TB":value>=1073741824?(value/1073741824).toFixed(1)+" GB":value>=1048576?(value/1048576).toFixed(0)+" MB":Math.max(0,Math.round(value/1024))+" KB";

export function SystemControlCenter({initialArea,platform,close=()=>{},embedded=false,notify,openPage,openFiles}:{initialArea:SystemControlArea;platform:string;close?:()=>void;embedded?:boolean;notify:(text:string,kind?:"info"|"error")=>void;openPage:(page:string)=>void;openApplications:()=>void;openFiles:(path:string)=>void;prepareTerminal:(command:string)=>void}){
  const [area,setArea]=useState<SystemControlArea>(initialArea),[busy,setBusy]=useState(""),[connectivity,setConnectivity]=useState<Connectivity>(emptyConnectivity),[displays,setDisplays]=useState<Display[]>([]),[devices,setDevices]=useState<AudioDevice[]>([]),[streams,setStreams]=useState<Stream[]>([]),[master,setMaster]=useState({volume:0,muted:false}),[processes,setProcesses]=useState<Process[]>([]),[drives,setDrives]=useState<Drive[]>([]),[,setSoftware]=useState<Software|null>(null),[,setApps]=useState<AppEntry[]>([]),[modules,setModules]=useState<ModuleEntry[]>([]),[locations,setLocations]=useState<Record<string,string>>({}),[selectedWifi,setSelectedWifi]=useState(""),[wifiSecret,setWifiSecret]=useState(""),[query,setQuery]=useState(""),[armedProcess,setArmedProcess]=useState(0),[meters,setMeters]=useState<Meter[]>([]),[details,setDetails]=useState<SystemDetails>({}),[sensors,setSensors]=useState<Sensor[]>([]),[telemetryStamp,setTelemetryStamp]=useState("");
  const tabRail=useRef<HTMLElement|null>(null);
  const get=async(path:string)=>{const response=await fetch("http://127.0.0.1:8765"+path),result=await response.json();if(!response.ok||result.error)throw new Error(result.error||"Local Core request failed");return result;};
  const post=async(path:string,data:Record<string,unknown>)=>{const response=await fetch("http://127.0.0.1:8765"+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),result=await response.json();if(!response.ok||result.ok===false||result.error)throw new Error(result.error||result.message||"Local Core command failed");return result;};
  const refresh=async(forceSoftware=false)=>{setBusy("refresh");const results=await Promise.allSettled([get("/api/connectivity"),get("/api/displays"),get("/api/audio-devices"),get("/api/audio"),get("/api/media"),get("/api/engineering"),get("/api/storage"),get("/api/software"+(forceSoftware?"?refresh=1":"")),get("/api/apps"),get("/api/extensions"),get("/api/system-locations"),get("/api/system"),get("/api/system-details")]);
    const value=(index:number)=>results[index].status==="fulfilled"?results[index].value:null,c=value(0);if(c)setConnectivity(c);const d=value(1);if(d)setDisplays(d.displays||[]);const a=value(2);if(a)setDevices(a.devices||[]);const m=value(3);if(m)setMaster({volume:Number(m.volume)||0,muted:Boolean(m.muted)});const media=value(4);if(media)setStreams(media.streams||[]);const e=value(5);if(e){setProcesses(e.processes||[]);setSensors(e.sensors||[]);}const s=value(6);if(s)setDrives(s.drives||[]);const sw=value(7);if(sw)setSoftware(sw);const ap=value(8);if(ap)setApps(ap.apps||[]);const mod=value(9);if(mod)setModules(mod.extensions||[]);const loc=value(10);if(loc)setLocations(loc);const system=value(11);if(system)setMeters(system.meters||[]);const hardware=value(12);if(hardware)setDetails(hardware);setTelemetryStamp(new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"}));setBusy("");};
  // The matrix is mounted fresh for each open action; its initial inventory is intentionally requested once.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer);},[]);
  useEffect(()=>{tabRail.current?.querySelector<HTMLElement>(`[data-system-area="${area}"]`)?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"nearest"});},[area]);
  const connectivityCommand=async(category:"wifi"|"bluetooth",action:string,id="")=>{setBusy(`${category}:${action}:${id}`);try{const result=await post("/api/connectivity-action",{category,action,id,secret:category==="wifi"?wifiSecret:""});if(result.state)setConnectivity(result.state);else setConnectivity(await get("/api/connectivity"));setWifiSecret("");notify(result.message||`${category} ${action} completed`);}catch(error){notify(error instanceof Error?error.message:"Connectivity command failed","error");}finally{setBusy("");}};
  const displayCommand=async(action:string,display?:Display)=>{setBusy(`display:${action}:${display?.id||""}`);try{const result=await post("/api/display-config",{action,id:display?.id||"",name:display?.name||""});setDisplays(result.displays||await get("/api/displays").then(value=>value.displays||[]));notify(result.message||"Display configuration changed");}catch(error){notify(error instanceof Error?error.message:"Display command failed","error");}finally{setBusy("");}};
  const simpleCommand=async(path:string,data:Record<string,unknown>,message:string,after:()=>Promise<void>)=>{setBusy(message);try{const result=await post(path,data);notify(result.message||message);await after();}catch(error){notify(error instanceof Error?error.message:message,"error");}finally{setBusy("");}};
  const selected=connectivity.wifi.networks.find(item=>item.id===selectedWifi||item.name===selectedWifi);
  const visibleProcesses=useMemo(()=>processes.filter(item=>item.name.toLowerCase().includes(query.toLowerCase())).slice(0,80),[processes,query]);
  const memory=details.memory,graphics=details.graphics||[],cores=details.cpu?.cores||[];
  const selectArea=(next:SystemControlArea)=>{setArea(next);setQuery("");};
  const stepArea=(direction:-1|1)=>{const current=areas.findIndex(item=>item[0]===area),next=(current+direction+areas.length)%areas.length;selectArea(areas[next][0]);};
  return <div className={embedded?"system-control-page":"system-control-backdrop"} role="presentation">
    <section className={`system-control-center${embedded?" embedded":""}`} role={embedded?"region":"dialog"} aria-modal={embedded?undefined:true} aria-label="LCARS System Control Matrix">
      <header><div><small>VERSION 31.3 · SYSTEMS AND SOFTWARE MATRIX</small><h2>LCARS SYSTEMS COMMAND</h2><p>Live telemetry, hardware inventory, package logistics, and workstation controls in one compact LCARS page.</p></div>{!embedded&&<button onClick={close}>CLOSE ×</button>}</header>
      <div className="system-control-tab-deck">
        <button className="system-control-tab-step previous" aria-label="Previous Systems section" title="Previous Systems section" onClick={()=>stepArea(-1)}>‹</button>
        <nav ref={tabRail} className="system-control-tabs" aria-label="Systems sections" onKeyDown={event=>{if(event.key==="ArrowLeft"){event.preventDefault();stepArea(-1);}if(event.key==="ArrowRight"){event.preventDefault();stepArea(1);}}}>{areas.map(([id,code,label],index)=><button type="button" data-system-area={id} aria-current={area===id?"page":undefined} aria-label={`${String(index+1).padStart(2,"0")} ${label}`} title={label} className={area===id?"active":""} onClick={()=>selectArea(id)} key={id}><i>{String(index+1).padStart(2,"0")}</i><span><small>{code}</small><b>{label}</b></span></button>)}</nav>
        <button className="system-control-tab-step next" aria-label="Next Systems section" title="Next Systems section" onClick={()=>stepArea(1)}>›</button>
      </div>
      <div className="system-control-toolbar"><b>{areas.find(item=>item[0]===area)?.[2]}</b><span>{platform}</span><button disabled={Boolean(busy)} onClick={()=>void refresh(area==="software")}>{busy?"PROCESSING…":"REFRESH MATRIX"}</button></div>
      <div className="system-control-body">
        {area==="telemetry"&&<section className="control-telemetry">
          <header><span><b>LIVE WORKSTATION TELEMETRY</b><small>{details.kernel||platform} · LAST SENSOR PASS {telemetryStamp||"PENDING"}</small></span><strong>{String(sensors.filter(sensor=>sensor.status==="ready").length).padStart(2,"0")} SYSTEMS READY</strong></header>
          <div className="telemetry-meter-grid">{meters.map((meter,index)=><article className={`telemetry-meter meter-${String(meter[0]).toLowerCase()}`} key={meter[0]}><i>{String(index+1).padStart(2,"0")}</i><span><small>{meter[2]}</small><b>{meter[0]}</b><em><u style={{width:`${Math.max(0,Math.min(100,Number(meter[1])||0))}%`}}/></em></span><strong>{meter[1]}%</strong></article>)}{!meters.length&&<p>LOCAL CORE TELEMETRY LINK PENDING</p>}</div>
          <div className="telemetry-detail-grid">
            <section className="telemetry-bank cpu-bank"><header><span><small>PROCESSOR MATRIX</small><b>{details.cpu?.logical||0} LOGICAL CORES</b></span><em>LOAD {details.cpu?.load?.length?details.cpu.load.join(" / "):"LIVE PER-CORE"}</em></header><div className="telemetry-core-grid">{cores.map((core,index)=><article key={core.name}><i>{String(index+1).padStart(2,"0")}</i><span><b>{core.name}</b><em><u style={{width:`${core.usage}%`}}/></em></span><strong>{core.usage}%</strong></article>)}{!cores.length&&<p>PER-CORE SENSOR DATA IS NOT REPORTED BY THIS PLATFORM</p>}</div></section>
            <section className="telemetry-bank memory-bank"><header><span><small>MEMORY ARCHITECTURE</small><b>{memory?.modules?.length||0} PHYSICAL MODULES</b></span><em>{memory?.percent||0}% ALLOCATED</em></header><div className="memory-summary"><span><small>TOTAL</small><b>{bytes(memory?.total||0)}</b></span><span><small>IN USE</small><b>{bytes(memory?.used||0)}</b></span><span><small>AVAILABLE</small><b>{bytes(memory?.available||0)}</b></span><span><small>SWAP</small><b>{bytes(memory?.swapUsed||0)} / {bytes(memory?.swapTotal||0)}</b></span></div><div className="telemetry-module-list">{memory?.modules?.map((module,index)=><article key={`${module.bank}:${index}`}><i>{String(index+1).padStart(2,"0")}</i><span><b>{module.bank||`MEMORY MODULE ${index+1}`}</b><small>{bytes(module.capacity)} · {module.speed?`${module.speed} MT/S · `:""}{module.manufacturer||"MANUFACTURER UNKNOWN"} {module.part||""}</small></span></article>)}{!memory?.modules?.length&&<p>MODULE-LEVEL INVENTORY REQUIRES PLATFORM HARDWARE REPORTING</p>}</div></section>
            <section className="telemetry-bank graphics-bank"><header><span><small>GRAPHICS MATRIX</small><b>{graphics.length} DISPLAY ADAPTER{graphics.length===1?"":"S"}</b></span><em>{graphics.reduce((total,item)=>total+(item.memoryTotal||0),0)?bytes(graphics.reduce((total,item)=>total+(item.memoryTotal||0),0))+" VRAM":"MEMORY NOT REPORTED"}</em></header><div>{graphics.map((adapter,index)=><article key={`${adapter.name}:${index}`}><i>{String(index+1).padStart(2,"0")}</i><span><small>{adapter.vendor||"GRAPHICS ADAPTER"}</small><b>{adapter.name}</b><em>{adapter.driver?`DRIVER ${adapter.driver}`:"DRIVER NOT REPORTED"} · {adapter.resolution||"DISPLAY MODE MANAGED"}</em></span><strong>{adapter.usage??0}%<small>{adapter.temperature==null?"TEMP N/A":`${adapter.temperature}°C`} · {bytes(adapter.memoryUsed||0)} / {bytes(adapter.memoryTotal||0)}</small></strong></article>)}{!graphics.length&&<p>NO DETAILED GRAPHICS TELEMETRY REPORTED</p>}</div></section>
            <section className="telemetry-bank sensor-bank"><header><span><small>ENGINEERING SENSOR ARRAY</small><b>THERMAL, POWER & SERVICE STATUS</b></span><em>{sensors.length} CHANNELS</em></header><div>{sensors.map((sensor,index)=><article className={sensor.status} key={sensor.id}><i>{String(index+1).padStart(2,"0")}</i><span><small>{sensor.kind.toUpperCase()}</small><b>{sensor.name}</b><em>{sensor.detail||"LOCAL SENSOR"}</em></span><strong>{sensor.value}</strong></article>)}{!sensors.length&&<p>NO OPTIONAL SENSOR ADAPTERS REPORTED · CORE TELEMETRY REMAINS ACTIVE</p>}</div></section>
            <section className="telemetry-bank storage-bank"><header><span><small>STORAGE TOPOLOGY</small><b>{drives.length} DETECTED VOLUMES</b></span><button onClick={()=>setArea("storage")}>OPEN STORAGE CONTROL</button></header><div>{drives.map((drive,index)=><article key={drive.id}><i>{drive.removable?"REM":String(index+1).padStart(2,"0")}</i><span><b>{drive.name}</b><small>{bytes(drive.size)} · {drive.filesystem||drive.type.toUpperCase()} · {drive.mounted?drive.mountpoints.join(", "):"NOT MOUNTED"}</small></span></article>)}</div></section>
          </div>
        </section>}
        {area==="network"&&<section className="control-network"><header><b>NETWORK INTERFACES</b><small>ADDRESSING, TRAFFIC, AND ROUTING STAY INSIDE LCARS</small></header><div>{(connectivity.wifi.interface||connectivity.wifi.available)&&<article><i>WF</i><span><b>{connectivity.wifi.interface||"WIRELESS"}</b><small>{connectivity.wifi.active||"NOT CONNECTED"}</small></span><em>{connectivity.wifi.enabled?"ONLINE":"OFFLINE"}</em><button onClick={()=>setArea("wifi")}>CONTROL</button></article>}<article><i>IP</i><span><b>LOCAL NETWORK LINK</b><small>Full interface telemetry remains on the Network page.</small></span><button onClick={()=>{close();openPage("network");}}>OPEN TELEMETRY</button></article><article><i>BT</i><span><b>BLUETOOTH RADIO</b><small>{connectivity.bluetooth.available?connectivity.bluetooth.enabled?"POWERED":"POWERED DOWN":connectivity.bluetooth.reason}</small></span><button onClick={()=>setArea("bluetooth")}>CONTROL</button></article></div></section>}
        {area==="wifi"&&<section className="control-wireless"><header><span><b>WI-FI CONTROL</b><small>{connectivity.wifi.interface||connectivity.wifi.reason}</small></span><nav><button disabled={!connectivity.wifi.control||Boolean(busy)} onClick={()=>void connectivityCommand("wifi",connectivity.wifi.enabled?"disable":"enable")}>{connectivity.wifi.enabled?"POWER OFF":"POWER ON"}</button><button disabled={!connectivity.wifi.control||!connectivity.wifi.enabled||Boolean(busy)} onClick={()=>void connectivityCommand("wifi","scan")}>SCAN</button></nav></header><div className="wireless-list">{connectivity.wifi.networks.map((network,index)=><button className={`${network.connected?"connected":""} ${selectedWifi===network.id?"selected":""}`} onClick={()=>{setSelectedWifi(network.id);setWifiSecret("");}} key={`${network.id}:${network.name}`}><i>{String(index+1).padStart(2,"0")}</i><span><b>{network.name}</b><small>{network.security} · {network.saved?"SAVED":"NEW NETWORK"}</small></span><em>{network.signal}%{network.connected?" · LINKED":""}</em></button>)}{!connectivity.wifi.networks.length&&<p>{connectivity.wifi.available?"NO WI-FI NETWORKS REPORTED · RUN SCAN":"WI-FI HARDWARE OR COMMAND CONTROL IS UNAVAILABLE"}</p>}</div>{selected&&<aside className="wireless-command"><span><small>SELECTED NETWORK</small><b>{selected.name}</b></span>{!selected.saved&&!selected.connected&&!selected.security.toLowerCase().includes("open")&&<label>NETWORK PASSWORD<input type="password" autoComplete="new-password" value={wifiSecret} onChange={event=>setWifiSecret(event.target.value)} placeholder="NOT STORED BY LCARS"/></label>}<button disabled={Boolean(busy)||(!selected.connected&&!selected.saved&&!selected.security.toLowerCase().includes("open")&&!wifiSecret)} onClick={()=>void connectivityCommand("wifi",selected.connected?"disconnect":"connect",selected.id)}>{selected.connected?"DISCONNECT":"CONNECT"}</button></aside>}</section>}
        {area==="bluetooth"&&<section className="control-wireless"><header><span><b>BLUETOOTH CONTROL</b><small>{connectivity.bluetooth.reason||"LOCAL DEVICE ASSOCIATION"}</small></span><nav><button disabled={!connectivity.bluetooth.control||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth",connectivity.bluetooth.enabled?"disable":"enable")}>{connectivity.bluetooth.enabled?"POWER OFF":"POWER ON"}</button><button disabled={!connectivity.bluetooth.control||!connectivity.bluetooth.enabled||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth","scan")}>SCAN 7 SEC</button></nav></header><div className="bluetooth-list">{connectivity.bluetooth.devices.map((device,index)=><article key={device.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{device.name}</b><small>{device.paired?"PAIRED":"AVAILABLE"}{device.trusted?" · TRUSTED":""}</small></span><em>{device.connected?"CONNECTED":"STANDBY"}</em><nav>{!device.paired&&<button disabled={!connectivity.bluetooth.control||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth","pair",device.id)}>PAIR</button>}<button disabled={!connectivity.bluetooth.control||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth",device.connected?"disconnect":"connect",device.id)}>{device.connected?"DISCONNECT":"CONNECT"}</button>{device.paired&&<button disabled={!connectivity.bluetooth.control||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth","remove",device.id)}>REMOVE</button>}</nav></article>)}{!connectivity.bluetooth.devices.length&&<p>{connectivity.bluetooth.available?"NO BLUETOOTH DEVICES REPORTED":"NO BLUETOOTH ADAPTER DETECTED"}</p>}</div></section>}
        {area==="audio"&&<section className="control-audio"><header><span><b>MASTER AUDIO BUS</b><small>OUTPUT, INPUT, AND APPLICATION STREAMS</small></span><strong>{master.muted?"MUTED":master.volume+"%"}</strong></header><input aria-label="Master audio volume" type="range" min="0" max="100" value={master.volume} onChange={event=>setMaster({...master,volume:+event.target.value})} onPointerUp={()=>void simpleCommand("/api/audio",{volume:master.volume},"Master volume changed",async()=>{})}/><button onClick={()=>void simpleCommand("/api/audio",{muted:!master.muted},master.muted?"Master audio restored":"Master audio muted",async()=>setMaster({...master,muted:!master.muted}))}>{master.muted?"RESTORE AUDIO":"MUTE OUTPUT"}</button><div className="audio-device-list">{devices.map(device=><article key={device.id}><i>{device.kind==="output"?"OUT":"IN"}</i><span><b>{device.name}</b><small>{device.default?"DEFAULT ":""}{device.kind.toUpperCase()}</small></span><button disabled={device.default||Boolean(busy)} onClick={()=>void simpleCommand("/api/audio-device",{id:device.id},"Audio device changed",async()=>{const next=await get("/api/audio-devices");setDevices(next.devices||[]);})}>{device.default?"ACTIVE":"MAKE DEFAULT"}</button></article>)}</div><h3>APPLICATION STREAMS</h3><div className="audio-stream-list">{streams.map(stream=><article key={stream.id}><span><b>{stream.group||stream.name}</b><small>{stream.name}</small></span><strong>{stream.volume}%</strong><input aria-label={`${stream.name} volume`} type="range" min="0" max="100" value={stream.volume} onChange={event=>setStreams(old=>old.map(item=>item.id===stream.id?{...item,volume:+event.target.value}:item))} onPointerUp={()=>void simpleCommand("/api/stream-volume",{id:stream.id,volume:stream.volume},"Application volume changed",async()=>{})}/><button onClick={()=>void simpleCommand("/api/stream-mute",{id:stream.id,muted:!stream.muted},"Application mute changed",async()=>setStreams(old=>old.map(item=>item.id===stream.id?{...item,muted:!item.muted}:item)))}>{stream.muted?"UNMUTE":"MUTE"}</button></article>)}{!streams.length&&<p>APPLICATION AUDIO STREAMS APPEAR HERE WHEN ACTIVE</p>}</div></section>}
        {area==="displays"&&<section className="control-displays"><header><b>DISPLAY CONFIGURATION</b><small>IDENTIFY, ROUTE, ROTATE, AND CHANGE TOPOLOGY WITHOUT A HOST SETTINGS WINDOW</small></header>{platform.includes("WINDOWS")&&<nav className="display-topologies">{[["topology-internal","PC ONLY"],["topology-clone","DUPLICATE"],["topology-extend","EXTEND"],["topology-external","SECOND ONLY"]].map(([id,label])=><button disabled={Boolean(busy)} key={id} onClick={()=>void displayCommand(id)}>{label}</button>)}</nav>}<div>{displays.map((display,index)=><article className={display.primary?"primary":""} key={display.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{display.name}</b><small>{display.geometry} · {display.source||"SYSTEM DISPLAY API"}</small></span><em>{display.primary?"PRIMARY":display.enabled?"ACTIVE":"DISABLED"}</em>{!platform.includes("WINDOWS")&&<nav><button disabled={Boolean(busy)||display.primary} onClick={()=>void displayCommand("primary",display)}>PRIMARY</button><button disabled={Boolean(busy)} onClick={()=>void displayCommand(display.enabled?"disable":"enable",display)}>{display.enabled?"DISABLE":"ENABLE"}</button><button disabled={Boolean(busy)||!display.enabled} onClick={()=>void displayCommand("rotate-left",display)}>↶ ROTATE</button><button disabled={Boolean(busy)||!display.enabled} onClick={()=>void displayCommand("rotate-normal",display)}>NORMAL</button></nav>}</article>)}</div><footer>NUMBERED CARDS ARE THE LCARS IDENTIFICATION OVERLAY. Windows exposes safe topology modes here; Linux exposes each KScreen/XRandR output.</footer></section>}
        {area==="software"&&<SoftwareLogistics notify={notify}/>}
        {area==="processes"&&<section className="control-processes"><header><b>PROCESS CONTROL</b><small>CURRENT-OPERATOR TASKS · CRITICAL LCARS PROCESSES PROTECTED</small></header><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="SEARCH PROCESSES…"/><div>{visibleProcesses.map(process=><article key={process.pid}><i>{process.pid}</i><span><b>{process.name}</b><small>{process.user} · {process.state.toUpperCase()}</small></span><em>CPU {process.cpu}% · MEM {process.memory}%</em><nav>{process.state==="stopped"?<button disabled={process.protected||Boolean(busy)} onClick={()=>void simpleCommand("/api/process-action",{pid:process.pid,action:"resume"},"Process resumed",async()=>{const data=await get("/api/engineering");setProcesses(data.processes||[]);})}>RESUME</button>:<button disabled={process.protected||Boolean(busy)} onClick={()=>void simpleCommand("/api/process-action",{pid:process.pid,action:"suspend"},"Process suspended",async()=>{const data=await get("/api/engineering");setProcesses(data.processes||[]);})}>SUSPEND</button>}<button className={armedProcess===process.pid?"armed":""} disabled={process.protected||Boolean(busy)} onClick={()=>armedProcess===process.pid?void simpleCommand("/api/process-action",{pid:process.pid,action:"terminate"},"Process terminated",async()=>{setArmedProcess(0);const data=await get("/api/engineering");setProcesses(data.processes||[]);}):setArmedProcess(process.pid)}>{armedProcess===process.pid?"CONFIRM END":"END"}</button></nav></article>)}</div></section>}
        {area==="storage"&&<section className="control-storage"><header><b>STORAGE MATRIX</b><small>PHYSICAL, REMOVABLE, AND MOUNTED FILESYSTEMS</small></header><div>{drives.map((drive,index)=><article key={drive.id}><i>{drive.removable?"REM":String(index+1).padStart(2,"0")}</i><span><b>{drive.name}</b><small>{bytes(drive.size)} · {drive.filesystem||drive.type.toUpperCase()} · {drive.mounted?drive.mountpoints.join(", "):"NOT MOUNTED"}</small></span>{drive.removable&&drive.type!=="disk"&&<button disabled={Boolean(busy)} onClick={()=>void simpleCommand("/api/storage-action",{id:drive.id,action:drive.mounted?"unmount":"mount"},drive.mounted?"Drive unmounted":"Drive mounted",async()=>{const data=await get("/api/storage");setDrives(data.drives||[]);})}>{drive.mounted?"UNMOUNT":"MOUNT"}</button>}</article>)}</div><button onClick={()=>{close();openPage("files");}}>OPEN LCARS FILES</button></section>}
        {area==="modules"&&<section className="control-modules"><header><b>MODULE PLATFORM</b><small>SIGNED, PERMISSIONED, AND ISOLATED LCARS EXTENSIONS</small></header><div>{modules.map((module,index)=><article key={module.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{module.name}</b><small>V{module.version} · {module.description}</small></span></article>)}{!modules.length&&<p>NO MODULES REPORTED BY THE LOCAL CORE</p>}</div><nav><button onClick={()=>{close();openPage("updates");}}>OPEN MODULE REPOSITORY</button><button disabled={!locations.extensions} onClick={()=>locations.extensions&&openFiles(locations.extensions)}>OPEN MODULE STORAGE IN LCARS FILES</button></nav></section>}
        {area==="media"&&<section className="control-media"><header><b>LCARS MEDIA DECK</b><small>LOCAL AUDIO AND VIDEO PLAYBACK REPLACES THE HOST MEDIA PLAYER</small></header><p>The integrated player supports files selected from LCARS Files, drag-and-drop, full-screen video, a fading LCARS HUD, seeking, volume, playback speed, and system media-session controls.</p><nav><button onClick={()=>{close();openPage("media");}}>OPEN MEDIA DECK</button><button onClick={()=>{close();openPage("files");}}>SELECT MEDIA IN LCARS FILES</button><button onClick={()=>setArea("audio")}>AUDIO ROUTING</button></nav></section>}
      </div>
      <footer><b>NO HOST CONTROL PANEL LAUNCHED</b><span>Platform-mandated security prompts may still appear when the operating system itself requires authorization.</span></footer>
    </section>
  </div>;
}
