"use client";

import { useEffect, useMemo, useState } from "react";

export type SystemControlArea = "network" | "wifi" | "bluetooth" | "audio" | "displays" | "software" | "processes" | "storage" | "modules" | "media";

type WifiNetwork={id:string;name:string;signal:number;security:string;connected:boolean;saved:boolean};
type BluetoothDevice={id:string;name:string;paired:boolean;connected:boolean;trusted:boolean};
type Connectivity={ok:boolean;platform:string;wifi:{available:boolean;enabled:boolean;active:string;interface:string;networks:WifiNetwork[];control:boolean;reason:string};bluetooth:{available:boolean;enabled:boolean;devices:BluetoothDevice[];control:boolean;reason:string}};
type Display={id:string;name:string;enabled:boolean;primary:boolean;geometry:string;source?:string};
type AudioDevice={id:string;name:string;default:boolean;kind:"output"|"input"};
type Stream={id:string;name:string;volume:number;group?:string;muted?:boolean};
type Process={pid:number;name:string;cpu:number;memory:number;user:string;state:string;protected:boolean};
type Drive={id:string;name:string;size:number;type:string;filesystem:string;mountpoints:string[];mounted:boolean;removable:boolean};
type Software={ok:boolean;manager:string;available:boolean;updates:{name:string;current:string;available:string}[];count:number;command:string;detail:string};
type AppEntry={id:string;name:string;comment:string};
type ModuleEntry={id:string;name:string;version:string;description:string};

const emptyConnectivity:Connectivity={ok:false,platform:"",wifi:{available:false,enabled:false,active:"",interface:"",networks:[],control:false,reason:"LOCAL CORE LINK REQUIRED"},bluetooth:{available:false,enabled:false,devices:[],control:false,reason:"LOCAL CORE LINK REQUIRED"}};
const areas:[SystemControlArea,string,string][]=[
  ["network","NET","NETWORK"],["wifi","WIFI","WI-FI"],["bluetooth","BT","BLUETOOTH"],["audio","AUD","AUDIO"],["displays","DSP","DISPLAYS"],
  ["software","SFT","SOFTWARE"],["processes","SYS","PROCESSES"],["storage","DRV","STORAGE"],["modules","MOD","MODULES"],["media","MED","MEDIA"],
];
const bytes=(value:number)=>value>=1099511627776?(value/1099511627776).toFixed(1)+" TB":value>=1073741824?(value/1073741824).toFixed(1)+" GB":value>=1048576?(value/1048576).toFixed(0)+" MB":Math.max(0,Math.round(value/1024))+" KB";

export function SystemControlCenter({initialArea,platform,close,notify,openPage,openApplications,openFiles,prepareTerminal}:{initialArea:SystemControlArea;platform:string;close:()=>void;notify:(text:string,kind?:"info"|"error")=>void;openPage:(page:string)=>void;openApplications:()=>void;openFiles:(path:string)=>void;prepareTerminal:(command:string)=>void}){
  const [area,setArea]=useState<SystemControlArea>(initialArea),[busy,setBusy]=useState(""),[connectivity,setConnectivity]=useState<Connectivity>(emptyConnectivity),[displays,setDisplays]=useState<Display[]>([]),[devices,setDevices]=useState<AudioDevice[]>([]),[streams,setStreams]=useState<Stream[]>([]),[master,setMaster]=useState({volume:0,muted:false}),[processes,setProcesses]=useState<Process[]>([]),[drives,setDrives]=useState<Drive[]>([]),[software,setSoftware]=useState<Software|null>(null),[apps,setApps]=useState<AppEntry[]>([]),[modules,setModules]=useState<ModuleEntry[]>([]),[locations,setLocations]=useState<Record<string,string>>({}),[selectedWifi,setSelectedWifi]=useState(""),[wifiSecret,setWifiSecret]=useState(""),[query,setQuery]=useState(""),[armedProcess,setArmedProcess]=useState(0);
  const get=async(path:string)=>{const response=await fetch("http://127.0.0.1:8765"+path),result=await response.json();if(!response.ok||result.error)throw new Error(result.error||"Local Core request failed");return result;};
  const post=async(path:string,data:Record<string,unknown>)=>{const response=await fetch("http://127.0.0.1:8765"+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),result=await response.json();if(!response.ok||result.ok===false||result.error)throw new Error(result.error||result.message||"Local Core command failed");return result;};
  const refresh=async(forceSoftware=false)=>{setBusy("refresh");const results=await Promise.allSettled([get("/api/connectivity"),get("/api/displays"),get("/api/audio-devices"),get("/api/audio"),get("/api/media"),get("/api/engineering"),get("/api/storage"),get("/api/software"+(forceSoftware?"?refresh=1":"")),get("/api/apps"),get("/api/extensions"),get("/api/system-locations")]);
    const value=(index:number)=>results[index].status==="fulfilled"?results[index].value:null,c=value(0);if(c)setConnectivity(c);const d=value(1);if(d)setDisplays(d.displays||[]);const a=value(2);if(a)setDevices(a.devices||[]);const m=value(3);if(m)setMaster({volume:Number(m.volume)||0,muted:Boolean(m.muted)});const media=value(4);if(media)setStreams(media.streams||[]);const e=value(5);if(e)setProcesses(e.processes||[]);const s=value(6);if(s)setDrives(s.drives||[]);const sw=value(7);if(sw)setSoftware(sw);const ap=value(8);if(ap)setApps(ap.apps||[]);const mod=value(9);if(mod)setModules(mod.extensions||[]);const loc=value(10);if(loc)setLocations(loc);setBusy("");};
  // The matrix is mounted fresh for each open action; its initial inventory is intentionally requested once.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer);},[]);
  const connectivityCommand=async(category:"wifi"|"bluetooth",action:string,id="")=>{setBusy(`${category}:${action}:${id}`);try{const result=await post("/api/connectivity-action",{category,action,id,secret:category==="wifi"?wifiSecret:""});if(result.state)setConnectivity(result.state);else setConnectivity(await get("/api/connectivity"));setWifiSecret("");notify(result.message||`${category} ${action} completed`);}catch(error){notify(error instanceof Error?error.message:"Connectivity command failed","error");}finally{setBusy("");}};
  const displayCommand=async(action:string,display?:Display)=>{setBusy(`display:${action}:${display?.id||""}`);try{const result=await post("/api/display-config",{action,id:display?.id||"",name:display?.name||""});setDisplays(result.displays||await get("/api/displays").then(value=>value.displays||[]));notify(result.message||"Display configuration changed");}catch(error){notify(error instanceof Error?error.message:"Display command failed","error");}finally{setBusy("");}};
  const simpleCommand=async(path:string,data:Record<string,unknown>,message:string,after:()=>Promise<void>)=>{setBusy(message);try{const result=await post(path,data);notify(result.message||message);await after();}catch(error){notify(error instanceof Error?error.message:message,"error");}finally{setBusy("");}};
  const selected=connectivity.wifi.networks.find(item=>item.id===selectedWifi||item.name===selectedWifi);
  const visibleApps=useMemo(()=>apps.filter(item=>(item.name+" "+item.comment).toLowerCase().includes(query.toLowerCase())).slice(0,80),[apps,query]);
  const visibleProcesses=useMemo(()=>processes.filter(item=>item.name.toLowerCase().includes(query.toLowerCase())).slice(0,80),[processes,query]);
  return <div className="system-control-backdrop" role="presentation">
    <section className="system-control-center" role="dialog" aria-modal="true" aria-label="LCARS System Control Matrix">
      <header><div><small>VERSION 30.11 · HOST-WINDOW REPLACEMENT</small><h2>LCARS SYSTEM CONTROL MATRIX</h2><p>Configure the workstation without leaving the command environment.</p></div><button onClick={close}>CLOSE ×</button></header>
      <nav className="system-control-tabs">{areas.map(([id,code,label],index)=><button className={area===id?"active":""} onClick={()=>{setArea(id);setQuery("");}} key={id}><i>{String(index+1).padStart(2,"0")}</i><span><small>{code}</small><b>{label}</b></span></button>)}</nav>
      <div className="system-control-toolbar"><b>{areas.find(item=>item[0]===area)?.[2]}</b><span>{platform}</span><button disabled={Boolean(busy)} onClick={()=>void refresh(area==="software")}>{busy?"PROCESSING…":"REFRESH MATRIX"}</button></div>
      <div className="system-control-body">
        {area==="network"&&<section className="control-network"><header><b>NETWORK INTERFACES</b><small>ADDRESSING, TRAFFIC, AND ROUTING STAY INSIDE LCARS</small></header><div>{(connectivity.wifi.interface||connectivity.wifi.available)&&<article><i>WF</i><span><b>{connectivity.wifi.interface||"WIRELESS"}</b><small>{connectivity.wifi.active||"NOT CONNECTED"}</small></span><em>{connectivity.wifi.enabled?"ONLINE":"OFFLINE"}</em><button onClick={()=>setArea("wifi")}>CONTROL</button></article>}<article><i>IP</i><span><b>LOCAL NETWORK LINK</b><small>Full interface telemetry remains on the Network page.</small></span><button onClick={()=>{close();openPage("network");}}>OPEN TELEMETRY</button></article><article><i>BT</i><span><b>BLUETOOTH RADIO</b><small>{connectivity.bluetooth.available?connectivity.bluetooth.enabled?"POWERED":"POWERED DOWN":connectivity.bluetooth.reason}</small></span><button onClick={()=>setArea("bluetooth")}>CONTROL</button></article></div></section>}
        {area==="wifi"&&<section className="control-wireless"><header><span><b>WI-FI CONTROL</b><small>{connectivity.wifi.interface||connectivity.wifi.reason}</small></span><nav><button disabled={!connectivity.wifi.control||Boolean(busy)} onClick={()=>void connectivityCommand("wifi",connectivity.wifi.enabled?"disable":"enable")}>{connectivity.wifi.enabled?"POWER OFF":"POWER ON"}</button><button disabled={!connectivity.wifi.control||!connectivity.wifi.enabled||Boolean(busy)} onClick={()=>void connectivityCommand("wifi","scan")}>SCAN</button></nav></header><div className="wireless-list">{connectivity.wifi.networks.map((network,index)=><button className={`${network.connected?"connected":""} ${selectedWifi===network.id?"selected":""}`} onClick={()=>{setSelectedWifi(network.id);setWifiSecret("");}} key={`${network.id}:${network.name}`}><i>{String(index+1).padStart(2,"0")}</i><span><b>{network.name}</b><small>{network.security} · {network.saved?"SAVED":"NEW NETWORK"}</small></span><em>{network.signal}%{network.connected?" · LINKED":""}</em></button>)}{!connectivity.wifi.networks.length&&<p>{connectivity.wifi.available?"NO WI-FI NETWORKS REPORTED · RUN SCAN":"WI-FI HARDWARE OR COMMAND CONTROL IS UNAVAILABLE"}</p>}</div>{selected&&<aside className="wireless-command"><span><small>SELECTED NETWORK</small><b>{selected.name}</b></span>{!selected.saved&&!selected.connected&&!selected.security.toLowerCase().includes("open")&&<label>NETWORK PASSWORD<input type="password" autoComplete="new-password" value={wifiSecret} onChange={event=>setWifiSecret(event.target.value)} placeholder="NOT STORED BY LCARS"/></label>}<button disabled={Boolean(busy)||(!selected.connected&&!selected.saved&&!selected.security.toLowerCase().includes("open")&&!wifiSecret)} onClick={()=>void connectivityCommand("wifi",selected.connected?"disconnect":"connect",selected.id)}>{selected.connected?"DISCONNECT":"CONNECT"}</button></aside>}</section>}
        {area==="bluetooth"&&<section className="control-wireless"><header><span><b>BLUETOOTH CONTROL</b><small>{connectivity.bluetooth.reason||"LOCAL DEVICE ASSOCIATION"}</small></span><nav><button disabled={!connectivity.bluetooth.control||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth",connectivity.bluetooth.enabled?"disable":"enable")}>{connectivity.bluetooth.enabled?"POWER OFF":"POWER ON"}</button><button disabled={!connectivity.bluetooth.control||!connectivity.bluetooth.enabled||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth","scan")}>SCAN 7 SEC</button></nav></header><div className="bluetooth-list">{connectivity.bluetooth.devices.map((device,index)=><article key={device.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{device.name}</b><small>{device.paired?"PAIRED":"AVAILABLE"}{device.trusted?" · TRUSTED":""}</small></span><em>{device.connected?"CONNECTED":"STANDBY"}</em><nav>{!device.paired&&<button disabled={!connectivity.bluetooth.control||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth","pair",device.id)}>PAIR</button>}<button disabled={!connectivity.bluetooth.control||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth",device.connected?"disconnect":"connect",device.id)}>{device.connected?"DISCONNECT":"CONNECT"}</button>{device.paired&&<button disabled={!connectivity.bluetooth.control||Boolean(busy)} onClick={()=>void connectivityCommand("bluetooth","remove",device.id)}>REMOVE</button>}</nav></article>)}{!connectivity.bluetooth.devices.length&&<p>{connectivity.bluetooth.available?"NO BLUETOOTH DEVICES REPORTED":"NO BLUETOOTH ADAPTER DETECTED"}</p>}</div></section>}
        {area==="audio"&&<section className="control-audio"><header><span><b>MASTER AUDIO BUS</b><small>OUTPUT, INPUT, AND APPLICATION STREAMS</small></span><strong>{master.muted?"MUTED":master.volume+"%"}</strong></header><input aria-label="Master audio volume" type="range" min="0" max="100" value={master.volume} onChange={event=>setMaster({...master,volume:+event.target.value})} onPointerUp={()=>void simpleCommand("/api/audio",{volume:master.volume},"Master volume changed",async()=>{})}/><button onClick={()=>void simpleCommand("/api/audio",{muted:!master.muted},master.muted?"Master audio restored":"Master audio muted",async()=>setMaster({...master,muted:!master.muted}))}>{master.muted?"RESTORE AUDIO":"MUTE OUTPUT"}</button><div className="audio-device-list">{devices.map(device=><article key={device.id}><i>{device.kind==="output"?"OUT":"IN"}</i><span><b>{device.name}</b><small>{device.default?"DEFAULT ":""}{device.kind.toUpperCase()}</small></span><button disabled={device.default||Boolean(busy)} onClick={()=>void simpleCommand("/api/audio-device",{id:device.id},"Audio device changed",async()=>{const next=await get("/api/audio-devices");setDevices(next.devices||[]);})}>{device.default?"ACTIVE":"MAKE DEFAULT"}</button></article>)}</div><h3>APPLICATION STREAMS</h3><div className="audio-stream-list">{streams.map(stream=><article key={stream.id}><span><b>{stream.group||stream.name}</b><small>{stream.name}</small></span><strong>{stream.volume}%</strong><input aria-label={`${stream.name} volume`} type="range" min="0" max="100" value={stream.volume} onChange={event=>setStreams(old=>old.map(item=>item.id===stream.id?{...item,volume:+event.target.value}:item))} onPointerUp={()=>void simpleCommand("/api/stream-volume",{id:stream.id,volume:stream.volume},"Application volume changed",async()=>{})}/><button onClick={()=>void simpleCommand("/api/stream-mute",{id:stream.id,muted:!stream.muted},"Application mute changed",async()=>setStreams(old=>old.map(item=>item.id===stream.id?{...item,muted:!item.muted}:item)))}>{stream.muted?"UNMUTE":"MUTE"}</button></article>)}{!streams.length&&<p>APPLICATION AUDIO STREAMS APPEAR HERE WHEN ACTIVE</p>}</div></section>}
        {area==="displays"&&<section className="control-displays"><header><b>DISPLAY CONFIGURATION</b><small>IDENTIFY, ROUTE, ROTATE, AND CHANGE TOPOLOGY WITHOUT A HOST SETTINGS WINDOW</small></header>{platform.includes("WINDOWS")&&<nav className="display-topologies">{[["topology-internal","PC ONLY"],["topology-clone","DUPLICATE"],["topology-extend","EXTEND"],["topology-external","SECOND ONLY"]].map(([id,label])=><button disabled={Boolean(busy)} key={id} onClick={()=>void displayCommand(id)}>{label}</button>)}</nav>}<div>{displays.map((display,index)=><article className={display.primary?"primary":""} key={display.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{display.name}</b><small>{display.geometry} · {display.source||"SYSTEM DISPLAY API"}</small></span><em>{display.primary?"PRIMARY":display.enabled?"ACTIVE":"DISABLED"}</em>{!platform.includes("WINDOWS")&&<nav><button disabled={Boolean(busy)||display.primary} onClick={()=>void displayCommand("primary",display)}>PRIMARY</button><button disabled={Boolean(busy)} onClick={()=>void displayCommand(display.enabled?"disable":"enable",display)}>{display.enabled?"DISABLE":"ENABLE"}</button><button disabled={Boolean(busy)||!display.enabled} onClick={()=>void displayCommand("rotate-left",display)}>↶ ROTATE</button><button disabled={Boolean(busy)||!display.enabled} onClick={()=>void displayCommand("rotate-normal",display)}>NORMAL</button></nav>}</article>)}</div><footer>NUMBERED CARDS ARE THE LCARS IDENTIFICATION OVERLAY. Windows exposes safe topology modes here; Linux exposes each KScreen/XRandR output.</footer></section>}
        {area==="software"&&<section className="control-software"><header><span><b>SOFTWARE LOGISTICS</b><small>{software?.detail||"PACKAGE INVENTORY PENDING"}</small></span><strong>{software?.count||0} UPDATES</strong></header><nav><button disabled={Boolean(busy)} onClick={()=>void refresh(true)}>SCAN PACKAGES</button><button onClick={openApplications}>APPLICATION LIBRARY · {apps.length}</button><button disabled={!software?.command} onClick={()=>software?.command&&prepareTerminal(software.command)}>PREPARE UPDATE IN LCARS TERMINAL</button></nav><label>SEARCH INSTALLED APPLICATIONS<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="APPLICATION NAME…"/></label><div className="software-updates"><h3>SYSTEM UPDATE CANDIDATES</h3>{software?.updates.map((item,index)=><article key={`${item.name}:${index}`}><i>{String(index+1).padStart(2,"0")}</i><span><b>{item.name}</b><small>{item.current} → {item.available}</small></span></article>)}{software&&!software.updates.length&&<p>NO PACKAGE UPDATES REPORTED BY {software.manager}</p>}</div><div className="software-apps"><h3>INSTALLED APPLICATIONS</h3>{visibleApps.map((app,index)=><article key={app.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{app.name}</b><small>{app.comment||app.id}</small></span></article>)}</div></section>}
        {area==="processes"&&<section className="control-processes"><header><b>PROCESS CONTROL</b><small>CURRENT-OPERATOR TASKS · CRITICAL LCARS PROCESSES PROTECTED</small></header><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="SEARCH PROCESSES…"/><div>{visibleProcesses.map(process=><article key={process.pid}><i>{process.pid}</i><span><b>{process.name}</b><small>{process.user} · {process.state.toUpperCase()}</small></span><em>CPU {process.cpu}% · MEM {process.memory}%</em><nav>{process.state==="stopped"?<button disabled={process.protected||Boolean(busy)} onClick={()=>void simpleCommand("/api/process-action",{pid:process.pid,action:"resume"},"Process resumed",async()=>{const data=await get("/api/engineering");setProcesses(data.processes||[]);})}>RESUME</button>:<button disabled={process.protected||Boolean(busy)} onClick={()=>void simpleCommand("/api/process-action",{pid:process.pid,action:"suspend"},"Process suspended",async()=>{const data=await get("/api/engineering");setProcesses(data.processes||[]);})}>SUSPEND</button>}<button className={armedProcess===process.pid?"armed":""} disabled={process.protected||Boolean(busy)} onClick={()=>armedProcess===process.pid?void simpleCommand("/api/process-action",{pid:process.pid,action:"terminate"},"Process terminated",async()=>{setArmedProcess(0);const data=await get("/api/engineering");setProcesses(data.processes||[]);}):setArmedProcess(process.pid)}>{armedProcess===process.pid?"CONFIRM END":"END"}</button></nav></article>)}</div></section>}
        {area==="storage"&&<section className="control-storage"><header><b>STORAGE MATRIX</b><small>PHYSICAL, REMOVABLE, AND MOUNTED FILESYSTEMS</small></header><div>{drives.map((drive,index)=><article key={drive.id}><i>{drive.removable?"REM":String(index+1).padStart(2,"0")}</i><span><b>{drive.name}</b><small>{bytes(drive.size)} · {drive.filesystem||drive.type.toUpperCase()} · {drive.mounted?drive.mountpoints.join(", "):"NOT MOUNTED"}</small></span>{drive.removable&&drive.type!=="disk"&&<button disabled={Boolean(busy)} onClick={()=>void simpleCommand("/api/storage-action",{id:drive.id,action:drive.mounted?"unmount":"mount"},drive.mounted?"Drive unmounted":"Drive mounted",async()=>{const data=await get("/api/storage");setDrives(data.drives||[]);})}>{drive.mounted?"UNMOUNT":"MOUNT"}</button>}</article>)}</div><button onClick={()=>{close();openPage("files");}}>OPEN LCARS FILES</button></section>}
        {area==="modules"&&<section className="control-modules"><header><b>MODULE PLATFORM</b><small>SIGNED, PERMISSIONED, AND ISOLATED LCARS EXTENSIONS</small></header><div>{modules.map((module,index)=><article key={module.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{module.name}</b><small>V{module.version} · {module.description}</small></span></article>)}{!modules.length&&<p>NO MODULES REPORTED BY THE LOCAL CORE</p>}</div><nav><button onClick={()=>{close();openPage("updates");}}>OPEN MODULE REPOSITORY</button><button disabled={!locations.extensions} onClick={()=>locations.extensions&&openFiles(locations.extensions)}>OPEN MODULE STORAGE IN LCARS FILES</button></nav></section>}
        {area==="media"&&<section className="control-media"><header><b>LCARS MEDIA DECK</b><small>LOCAL AUDIO AND VIDEO PLAYBACK REPLACES THE HOST MEDIA PLAYER</small></header><p>The integrated player supports files selected from LCARS Files, drag-and-drop, full-screen video, a fading LCARS HUD, seeking, volume, playback speed, and system media-session controls.</p><nav><button onClick={()=>{close();openPage("media");}}>OPEN MEDIA DECK</button><button onClick={()=>{close();openPage("files");}}>SELECT MEDIA IN LCARS FILES</button><button onClick={()=>setArea("audio")}>AUDIO ROUTING</button></nav></section>}
      </div>
      <footer><b>NO HOST CONTROL PANEL LAUNCHED</b><span>Platform-mandated security prompts may still appear when the operating system itself requires authorization.</span></footer>
    </section>
  </div>;
}
