"use client";

import { useEffect, useMemo, useState } from "react";
import type { UniversalSearchCategory, UniversalSearchEntry } from "./v30-search-core";

export type FabricDevice={id:string;name:string;online?:boolean;transport?:string;queuedDeliveries?:number};
export type FabricProcedure={id:string;name:string};
export type FabricStatus={
  ok:boolean;transport:string;storage:string;categories:Record<string,boolean>;conflictPolicy:"ask"|"newest"|"local";
  recent:{id:string;category:string;name:string;detail:string;station:string;updatedAt:number}[];
  history:{id:string;action:string;category:string;detail:string;status:string;station:string;createdAt:number}[];
  conflicts:{id:string;category:string;name:string;localStation:string;incomingStation:string;createdAt:number}[];
  privateItems:{id:string;name:string;updatedAt:number;versionCount:number}[];
  diagnostics:{recentItems:number;historyEntries:number;openConflicts:number;privateItems:number;versionedRecords:number};
};

const categories:{id:UniversalSearchCategory;label:string}[]=[
  {id:"applications",label:"APPS"},{id:"files",label:"FILES"},{id:"settings",label:"SETTINGS"},{id:"commands",label:"COMMANDS"},
  {id:"stations",label:"STATIONS"},{id:"notifications",label:"NOTICES"},{id:"media",label:"MEDIA"},{id:"contacts",label:"CONTACTS"},
  {id:"modules",label:"MODULES"},{id:"procedures",label:"PROCEDURES"},{id:"activity",label:"HISTORY"},
];
const policyLabels:Record<string,string>={applications:"APPLICATIONS",files:"FILES",recentItems:"RECENT ITEMS",settings:"SETTINGS",commands:"COMMANDS",stations:"STATIONS",notifications:"NOTIFICATIONS",media:"MEDIA",contacts:"CONTACTS",modules:"MODULES",procedures:"PROCEDURES",activity:"ACTIVITY HISTORY",clipboard:"CLIPBOARD HANDOFF",smallFiles:"SMALL FILES",privateStorage:"PRIVATE STORAGE"};
const time=(stamp:number)=>stamp?new Date(stamp*(stamp<100000000000?1000:1)).toLocaleString():"UNKNOWN";

export function UniversalSearch({query,setQuery,results,filesLoading,devices,procedures,fabric,close,run,refreshFabric,updatePolicy,sendClipboard,savePrivate,deletePrivate,resolveConflict}:{
  query:string;setQuery:(value:string)=>void;results:UniversalSearchEntry[];filesLoading:boolean;devices:FabricDevice[];procedures:FabricProcedure[];fabric:FabricStatus|null;close:()=>void;
  run:(result:UniversalSearchEntry,action:string,target?:string)=>void;refreshFabric:()=>void;updatePolicy:(categories:Record<string,boolean>,conflictPolicy:FabricStatus["conflictPolicy"])=>void;
  sendClipboard:(deviceId:string,text:string)=>void;savePrivate:(name:string,content:string)=>void;deletePrivate:(id:string)=>void;resolveConflict:(id:string,resolution:"local"|"incoming"|"both")=>void;
}){
  const [area,setArea]=useState<"search"|"fabric"|"private">("search"),[category,setCategory]=useState<UniversalSearchCategory|null>(null),[route,setRoute]=useState<UniversalSearchEntry|null>(null),[attach,setAttach]=useState<UniversalSearchEntry|null>(null),[clipboard,setClipboard]=useState(""),[privateName,setPrivateName]=useState(""),[privateContent,setPrivateContent]=useState("");
  const visible=useMemo(()=>category?results.filter((item)=>item.category===category):results,[category,results]);
  useEffect(()=>{if(area!=="search")refreshFabric();},[area]);
  const actionSet=(item:UniversalSearchEntry)=>item.category==="files"?["open-here","open-on-padd","send-station","attach-procedure"]:item.category==="applications"?["open"]:item.category==="procedures"?["preview","attach-builder"]:item.category==="notifications"?["open","mark-read"]:item.category==="media"?["open","play-pause"]:item.category==="stations"||item.category==="contacts"?["open","send-clipboard"]:item.category==="commands"?["prepare"]:item.category==="modules"?["open","settings"]:["open"];
  const label=(action:string)=>({"open-here":"OPEN HERE","open-on-padd":"OPEN ON PADD","send-station":"SEND TO STATION","attach-procedure":"ATTACH TO PROCEDURE","play-pause":"PLAY / PAUSE","mark-read":"MARK READ","attach-builder":"OPEN BUILDER",prepare:"PREPARE COMMAND",open:"OPEN",preview:"PREVIEW",settings:"SETTINGS","send-clipboard":"SEND CLIPBOARD"}[action]||action.toUpperCase());
  const trigger=(item:UniversalSearchEntry,action:string)=>{
    if(["open-on-padd","send-station","send-clipboard"].includes(action)&&devices.length){setRoute(item);return;}
    if(action==="attach-procedure"&&procedures.length){setAttach(item);return;}
    run(item,action);
  };
  return <div className="backdrop universal-search-backdrop" onMouseDown={(event)=>event.target===event.currentTarget&&close()}>
    <section className="universal-search" role="dialog" aria-modal="true" aria-label="Universal LCARS Search and Data Fabric">
      <header><div><small>VERSION 30.6 · UNIVERSAL LCARS INDEX</small><h2>SEARCH + DATA FABRIC</h2><p>Find, act, route, synchronize, and recover information across this command environment.</p></div><button onClick={close}>CLOSE ×</button></header>
      <nav className="universal-search-tabs">{([['search','SEARCH'],['fabric','DATA FABRIC'],['private','PRIVATE STORAGE']] as const).map(([id,name])=><button className={area===id?"active":""} onClick={()=>setArea(id)} key={id}>{name}</button>)}</nav>
      {area==="search"&&<main className="universal-search-main">
        <section className="universal-search-query"><input autoFocus value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="SEARCH APPLICATIONS, FILES, SETTINGS, COMMANDS, STATIONS, NOTICES…"/><b>{filesLoading?"INDEXING LOCAL FILES…":`${visible.length} ACTIONABLE RESULT${visible.length===1?"":"S"}`}</b></section>
        <nav className="universal-search-categories"><button className={!category?"active":""} onClick={()=>setCategory(null)}>ALL</button>{categories.map((item)=><button className={category===item.id?"active":""} onClick={()=>setCategory(category===item.id?null:item.id)} key={item.id}>{item.label}<i>{results.filter((result)=>result.category===item.id).length}</i></button>)}</nav>
        <div className="universal-search-results">{visible.map((item,index)=><article key={`${item.category}:${item.id}`}><i>{String(index+1).padStart(2,"0")}</i><span><small>{item.category.toUpperCase()}</small><b>{item.title}</b><p>{item.detail}</p></span><nav>{actionSet(item).map((action)=>{const unavailable=["open-on-padd","send-station","send-clipboard"].includes(action)&&!devices.length||action==="attach-procedure"&&!procedures.length;return <button disabled={unavailable} title={unavailable?action==="attach-procedure"?"Create a Procedure first":"Pair a trusted station first":undefined} onClick={()=>trigger(item,action)} key={action}>{label(action)}</button>;})}</nav></article>)}{!visible.length&&<p className="universal-empty">NO MATCHING RECORDS · TRY A NAME, FILE TYPE, SETTING, STATION, OR COMMAND</p>}</div>
      </main>}
      {area==="fabric"&&<main className="data-fabric-main">
        <section className="fabric-summary"><article><small>TRANSPORT</small><b>{fabric?.transport||"LOCAL CORE"}</b><p>Signed, authenticated station envelopes.</p></article><article><small>RECENT ITEMS</small><b>{fabric?.diagnostics.recentItems||0}</b><p>Bounded cross-category recall.</p></article><article><small>OPEN CONFLICTS</small><b>{fabric?.diagnostics.openConflicts||0}</b><p>Nothing is overwritten silently.</p></article><article><small>VERSIONED RECORDS</small><b>{fabric?.diagnostics.versionedRecords||0}</b><p>Up to twenty versions per record.</p></article></section>
        <section className="fabric-policy"><header><span><small>PER-CATEGORY SYNCHRONIZATION</small><b>ROUTING POLICY</b></span><label>CONFLICT HANDLING<select value={fabric?.conflictPolicy||"ask"} onChange={(event)=>fabric&&updatePolicy(fabric.categories,event.target.value as FabricStatus["conflictPolicy"])}><option value="ask">ASK EVERY TIME</option><option value="newest">KEEP NEWEST</option><option value="local">PREFER THIS STATION</option></select></label></header><div>{Object.entries(fabric?.categories||{}).map(([id,enabled])=><label key={id}><input type="checkbox" checked={enabled} onChange={(event)=>fabric&&updatePolicy({...fabric.categories,[id]:event.target.checked},fabric.conflictPolicy)}/><span>{policyLabels[id]||id.toUpperCase()}</span></label>)}</div></section>
        <section className="fabric-transfer"><header><span><small>ENCRYPTED STATION HANDOFF</small><b>CLIPBOARD + SMALL FILE ROUTING</b></span><em>{devices.length} TRUSTED STATION{devices.length===1?"":"S"}</em></header><textarea value={clipboard} onChange={(event)=>setClipboard(event.target.value)} maxLength={4000} placeholder="TEXT TO HAND OFF…"/><div>{devices.map((device)=><button disabled={!clipboard.trim()||device.transport!=="aes-256-gcm"||!fabric?.categories.clipboard} onClick={()=>{sendClipboard(device.id,clipboard);setClipboard("");}} key={device.id}><b>{device.name}</b><small>{device.online?"ONLINE":"OFFLINE QUEUE"} · {device.transport?.toUpperCase()||"TRANSPORT UNKNOWN"}</small></button>)}{!devices.length&&<p>PAIR A TRUSTED PADD OR STATION TO ROUTE DATA</p>}</div></section>
        <div className="fabric-lists"><section><header><b>RECENT ITEM SYNCHRONIZATION</b></header>{fabric?.recent.map((item)=><article key={`${item.category}:${item.id}`}><span><small>{item.category.toUpperCase()} · {item.station}</small><b>{item.name}</b><p>{item.detail}</p></span><em>{time(item.updatedAt)}</em></article>)}{!fabric?.recent.length&&<p>NO RECENT ITEMS RECORDED</p>}</section><section><header><b>CONFLICT RESOLUTION</b></header>{fabric?.conflicts.map((item)=><article key={item.id}><span><small>{item.category.toUpperCase()}</small><b>{item.name}</b><p>{item.localStation} ↔ {item.incomingStation}</p></span><nav><button onClick={()=>resolveConflict(item.id,"local")}>KEEP LOCAL</button><button onClick={()=>resolveConflict(item.id,"incoming")}>USE INCOMING</button><button onClick={()=>resolveConflict(item.id,"both")}>KEEP BOTH</button></nav></article>)}{!fabric?.conflicts.length&&<p>NO UNRESOLVED CONFLICTS</p>}</section></div>
      </main>}
      {area==="private"&&<main className="private-storage-main"><header><span><small>LOCAL AES-256-GCM VAULT</small><b>ENCRYPTED PRIVATE STORAGE</b><p>Content is encrypted at rest with a station-local key. Private storage remains opt-in and follows its own synchronization control.</p></span><em>{fabric?.storage||"INITIALIZING"}</em></header>{fabric?.categories.privateStorage?<><section><input value={privateName} onChange={(event)=>setPrivateName(event.target.value)} maxLength={100} placeholder="PRIVATE RECORD NAME"/><textarea value={privateContent} onChange={(event)=>setPrivateContent(event.target.value)} maxLength={32768} placeholder="ENCRYPTED CONTENT…"/><button disabled={!privateName.trim()||!privateContent.trim()} onClick={()=>{savePrivate(privateName,privateContent);setPrivateName("");setPrivateContent("");}}>SAVE ENCRYPTED RECORD</button></section><div>{fabric.privateItems.map((item,index)=><article key={item.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{item.name}</b><small>{item.versionCount} VERSION{item.versionCount===1?"":"S"} · UPDATED {time(item.updatedAt)}</small></span><button onClick={()=>deletePrivate(item.id)}>DELETE</button></article>)}{!fabric.privateItems.length&&<p>PRIVATE STORAGE IS EMPTY</p>}</div></>:<section className="private-storage-disabled"><b>PRIVATE STORAGE DISABLED</b><p>Enable PRIVATE STORAGE in Data Fabric routing policy. No private record is created or synchronized until you opt in.</p><button onClick={()=>fabric&&updatePolicy({...fabric.categories,privateStorage:true},fabric.conflictPolicy)}>ENABLE PRIVATE STORAGE</button></section>}</main>}
      {route&&<aside className="search-route-picker"><header><span><small>SELECT TRUSTED DESTINATION</small><b>{route.title}</b></span><button onClick={()=>setRoute(null)}>CANCEL ×</button></header>{devices.map((device)=>{const disabled=route.category==="files"?(device.transport!=="aes-256-gcm"||!fabric?.categories.smallFiles):!fabric?.categories.clipboard;return <button disabled={disabled} title={disabled?route.category==="files"?"Enable Small Files and use an encrypted Federation link":"Enable Clipboard Handoff in Data Fabric":undefined} key={device.id} onClick={()=>{run(route,route.category==="files"?"send-station":"send-clipboard",device.id);setRoute(null);}}><b>{device.name}</b><small>{device.online?"ONLINE":"OFFLINE · QUEUE DELIVERY"} · {device.transport?.toUpperCase()||"UNKNOWN"}</small></button>;})}</aside>}
      {attach&&<aside className="search-route-picker"><header><span><small>ATTACH FILE TO PROCEDURE</small><b>{attach.title}</b></span><button onClick={()=>setAttach(null)}>CANCEL ×</button></header>{procedures.map((procedure)=><button key={procedure.id} onClick={()=>{run(attach,"attach-procedure",procedure.id);setAttach(null);}}><b>{procedure.name}</b><small>ADD AS A VERSIONED PROCEDURE RESOURCE</small></button>)}</aside>}
      <footer><span>CTRL/⌘ F · OPEN SEARCH</span><span>AES-256-GCM · OPT-IN ROUTES · LOCAL-FIRST INDEX</span></footer>
    </section>
  </div>;
}
