"use client";

import { useCallback, useEffect, useState } from "react";

type Mode="overview"|"connections"|"hardware"|"diagnostics";
type Connection={id:string;name:string;kind:string;active:boolean;device:string;autoconnect:boolean;metered:string;meteredControl:boolean};
type Device={id:string;name:string;state?:string;detail?:string;default?:boolean;mounted?:boolean;mountpoints?:string[];size?:number;filesystem?:string};
type Status={ok:boolean;version:string;platform:string;capabilities:Record<string,boolean>;connections:{vpn:Connection[];savedNetworks:Connection[];hotspot:{available:boolean;active:boolean;name:string;interface:string;control:boolean;reason:string};firewall:{available:boolean;active:boolean;provider:string;profiles:string[];detail:string}};hardware:{printers:Device[];scanners:Device[];cameras:Device[];controllers:Device[];usb:Device[];removable:Device[]};policy:{removable:"ask"|"allow"|"block";scope:string};diagnostics:{ranAt:number;gateway:string;dns:string;internet:string;latencyMs:number|null;detail:string;durationMs?:number}};
type Pending={id:string;action:string;target:string;label:string};
type PortalKind="camera"|"screen-share"|"print"|"authorize";

const CORE="http://127.0.0.1:8765";
const approvalKey=(action:string,target:string)=>`lcars-connectivity-approval:${action}:${target}`;
const size=(value=0)=>value>=1099511627776?`${(value/1099511627776).toFixed(1)} TB`:value>=1073741824?`${(value/1073741824).toFixed(1)} GB`:value>=1048576?`${(value/1048576).toFixed(0)} MB`:`${Math.round(value/1024)} KB`;

export function ConnectivityHardware({notify,openPortal,openWifi,openBluetooth}:{notify:(text:string,kind?:"info"|"error")=>void;openPortal:()=>void;openWifi:()=>void;openBluetooth:()=>void}){
  const [mode,setMode]=useState<Mode>("overview"),[status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(""),[error,setError]=useState(""),[pending,setPending]=useState<Pending|null>(null),[hotspotName,setHotspotName]=useState("LCARS-NETWORK"),[hotspotSecret,setHotspotSecret]=useState("");
  const request=useCallback(async(path:string,options?:RequestInit)=>{const response=await fetch(CORE+path,options),value=await response.json();if(!response.ok||value.ok===false||value.error)throw new Error(value.error||"Local Core request failed");return value;},[]);
  const refresh=useCallback(async(force=false)=>{setBusy("refresh");setError("");try{setStatus(await request(`/api/connectivity-hardware${force?"?refresh=1":""}`));}catch(caught){setError(caught instanceof Error?caught.message:"Connectivity inventory is unavailable");}finally{setBusy("");}},[request]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(false),0);return()=>window.clearTimeout(timer);},[refresh]);
  const post=async(body:Record<string,unknown>)=>request("/api/connectivity-hardware",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
  const protectedAction=async(action:string,target:string,label:string,extra:Record<string,unknown>={})=>{
    const key=approvalKey(action,target);setBusy(key);setError("");
    try{
      const stored=window.sessionStorage.getItem(key);
      if(stored){
        const result=await request(`/api/portal-request?id=${encodeURIComponent(stored)}`),approval=result.request;
        if(approval?.decision==="waiting"){setPending({id:stored,action,target,label});notify("Connection request is still awaiting Portal approval");return;}
        if(approval?.decision==="approved"){
          const value=await post({operation:"execute",action,target,approvalId:stored,...extra});window.sessionStorage.removeItem(key);setPending(null);setStatus(value.status||await request("/api/connectivity-hardware?refresh=1"));setHotspotSecret("");notify(value.message||`${label} completed`);return;
        }
        window.sessionStorage.removeItem(key);
      }
      const value=await post({operation:"request",action,target,...extra}),approval=value.request as {id:string};window.sessionStorage.setItem(key,approval.id);setPending({id:approval.id,action,target,label});notify(`${label} sent to Portal Center for approval`);
    }catch(caught){const message=caught instanceof Error?caught.message:`${label} failed`;if(/already been used|no longer present|not found/i.test(message))window.sessionStorage.removeItem(key);setError(message);notify(message,"error");}finally{setBusy("");}
  };
  const localAction=async(body:Record<string,unknown>,success:string)=>{setBusy(String(body.operation||"operation"));setError("");try{const value=await post(body);if(value.status)setStatus(value.status);else if(value.diagnostics)setStatus(current=>current?{...current,diagnostics:value.diagnostics}:current);notify(value.message||success);}catch(caught){const message=caught instanceof Error?caught.message:success;setError(message);notify(message,"error");}finally{setBusy("");}};
  const portalRequest=async(kind:PortalKind,title:string,detail:string,payload:Record<string,unknown>)=>{setBusy(`portal:${kind}`);try{await request("/api/portal-operation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"submit",kind,client:"LCARS CONNECTIVITY AND HARDWARE",title,detail,payload})});notify(`${title} sent to Portal Center`);}catch(caught){notify(caught instanceof Error?caught.message:"Portal request failed","error");}finally{setBusy("");}};
  const hardwareGroups:[string,keyof Status["hardware"],PortalKind][]=[["PRINTERS","printers","print"],["SCANNERS","scanners","authorize"],["CAMERAS","cameras","camera"],["GAME CONTROLLERS","controllers","authorize"],["USB DEVICES","usb","authorize"],["REMOVABLE STORAGE","removable","authorize"]];
  const totalDevices=status?Object.values(status.hardware).reduce((total,items)=>total+items.length,0):0;
  return <section className="connectivity-hardware">
    <header className="connectivity-command-header"><span><small>VERSION 31.4 · CONNECTIVITY AND HARDWARE</small><b>STATION LINK MATRIX</b><em>{status?`${status.platform.toUpperCase()} · CAPABILITY-AWARE`:`AWAITING LOCAL CORE`}</em></span><strong>{String(totalDevices).padStart(2,"0")} DEVICES</strong></header>
    <nav className="connectivity-modes" aria-label="Connectivity and Hardware sections">{(["overview","connections","hardware","diagnostics"] as Mode[]).map((item,index)=><button type="button" key={item} className={mode===item?"active":""} aria-current={mode===item?"page":undefined} onClick={()=>setMode(item)}><i>{String(index+1).padStart(2,"0")}</i><span>{item.toUpperCase()}</span></button>)}<button type="button" disabled={Boolean(busy)} onClick={()=>void refresh(true)}>{busy==="refresh"?"SCANNING…":"REFRESH MATRIX"}</button></nav>
    {error&&<p className="connectivity-error">● {error}</p>}
    {pending&&<aside className="connectivity-approval"><span><small>PORTAL AUTHORIZATION REQUIRED</small><b>{pending.label}</b><em>Approve the request, return here, then select the command again to execute it.</em></span><button onClick={openPortal}>OPEN PORTAL CENTER</button><button disabled={Boolean(busy)} onClick={()=>void protectedAction(pending.action,pending.target,pending.label,pending.action==="hotspot-start"?{ssid:hotspotName,secret:hotspotSecret}:{})}>CHECK APPROVAL + EXECUTE</button></aside>}
    {mode==="overview"&&<div className="connectivity-overview">
      <article className={status?.connections.firewall.active?"ready":"attention"}><i>01</i><span><small>FIREWALL</small><b>{status?.connections.firewall.provider||"NO ADAPTER"}</b><em>{status?.connections.firewall.active?"PROTECTED":status?.connections.firewall.available?"INACTIVE":"UNAVAILABLE"}</em></span></article>
      <article className={status?.connections.hotspot.active?"ready":""}><i>02</i><span><small>HOTSPOT</small><b>{status?.connections.hotspot.active?status.connections.hotspot.name:"STANDBY"}</b><em>{status?.connections.hotspot.control?"CONTROL READY":status?.connections.hotspot.reason||"UNAVAILABLE"}</em></span></article>
      <article><i>03</i><span><small>SECURE TUNNELS</small><b>{status?.connections.vpn.filter(item=>item.active).length||0} ACTIVE</b><em>{status?.connections.vpn.length||0} VPN PROFILES</em></span></article>
      <article><i>04</i><span><small>DEVICE INVENTORY</small><b>{totalDevices} DETECTED</b><em>PORTAL-ROUTED ACCESS</em></span></article>
      <section className="connectivity-quick"><button onClick={openWifi}>WI-FI CONTROL</button><button onClick={openBluetooth}>BLUETOOTH CONTROL</button><button onClick={()=>void portalRequest("screen-share","SCREEN SHARING REQUEST","Allow a selected display to be shared with an LCARS application or trusted station.",{source:"systems-matrix"})}>REQUEST SCREEN SHARE</button><button onClick={openPortal}>PORTAL CENTER</button></section>
    </div>}
    {mode==="connections"&&<div className="connection-grid">
      <section className="connection-bank"><header><span><small>PROTECTED CONNECTIONS</small><b>VPN PROFILES</b></span><em>{status?.connections.vpn.length||0} DETECTED</em></header><div>{status?.connections.vpn.map((item,index)=><article key={item.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{item.name}</b><small>{item.kind.toUpperCase()} · {item.device||"STORED PROFILE"}</small></span><em>{item.active?"CONNECTED":"STANDBY"}</em><button disabled={Boolean(busy)} onClick={()=>void protectedAction(item.active?"vpn-disconnect":"vpn-connect",item.id,item.active?`DISCONNECT ${item.name}`:`CONNECT ${item.name}`)}>{item.active?"REQUEST DISCONNECT":"REQUEST CONNECT"}</button></article>)}{status&&!status.connections.vpn.length&&<p>NO VPN OR WIREGUARD PROFILES WERE REPORTED BY THIS PLATFORM.</p>}</div></section>
      <section className="connection-bank hotspot-bank"><header><span><small>LOCAL ACCESS POINT</small><b>HOTSPOT CONTROL</b></span><em>{status?.connections.hotspot.active?"ACTIVE":"STANDBY"}</em></header>{status?.connections.hotspot.active?<div className="hotspot-active"><b>{status.connections.hotspot.name}</b><small>{status.connections.hotspot.interface}</small><button disabled={Boolean(busy)} onClick={()=>void protectedAction("hotspot-stop","","STOP HOTSPOT")}>REQUEST STOP</button></div>:<form onSubmit={event=>{event.preventDefault();void protectedAction("hotspot-start","","START HOTSPOT",{ssid:hotspotName,secret:hotspotSecret});}}><label>NETWORK NAME<input maxLength={32} value={hotspotName} onChange={event=>setHotspotName(event.target.value)}/></label><label>PASSWORD · NEVER STORED<input type="password" minLength={8} maxLength={63} autoComplete="new-password" value={hotspotSecret} onChange={event=>setHotspotSecret(event.target.value)}/></label><button disabled={!status?.connections.hotspot.control||hotspotName.length<1||hotspotSecret.length<8||Boolean(busy)}>REQUEST HOTSPOT</button><small>{status?.connections.hotspot.reason||`ADAPTER ${status?.connections.hotspot.interface||"PENDING"}`}</small></form>}</section>
      <section className="connection-bank saved-bank"><header><span><small>AUTOMATIC LINK POLICY</small><b>SAVED NETWORKS</b></span><em>{status?.connections.savedNetworks.length||0} PROFILES</em></header><div>{status?.connections.savedNetworks.map((item,index)=><article key={item.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{item.name}</b><small>{item.autoconnect?"AUTO-CONNECT":"MANUAL"} · METERED {item.metered.toUpperCase()}</small></span><em>{item.active?"ACTIVE":"SAVED"}</em><nav><button disabled={!item.meteredControl||Boolean(busy)} onClick={()=>void protectedAction("set-metered",item.id,`SET ${item.name} METERED`,{metered:"yes"})}>METERED</button><button disabled={!item.meteredControl||Boolean(busy)} onClick={()=>void protectedAction("set-metered",item.id,`SET ${item.name} UNMETERED`,{metered:"no"})}>UNMETERED</button><button className="danger" disabled={Boolean(busy)||item.active} onClick={()=>void protectedAction("forget-network",item.id,`FORGET ${item.name}`)}>FORGET</button></nav></article>)}{status&&!status.connections.savedNetworks.length&&<p>NO SAVED WI-FI PROFILES WERE REPORTED.</p>}</div></section>
    </div>}
    {mode==="hardware"&&<div className="hardware-grid">{hardwareGroups.map(([title,key,kind],groupIndex)=><section className="hardware-bank" key={key}><header><span><small>DEVICE CHANNEL {String(groupIndex+1).padStart(2,"0")}</small><b>{title}</b></span><em>{status?.hardware[key].length||0}</em></header><div>{status?.hardware[key].map((item,index)=><article key={item.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{item.name}</b><small>{key==="removable"?`${size(item.size)} · ${item.filesystem||"FILESYSTEM"} · ${item.mounted?item.mountpoints?.join(", "):"NOT MOUNTED"}`:item.detail||item.state||"DETECTED"}</small></span>{key!=="removable"&&<button disabled={Boolean(busy)} onClick={()=>void portalRequest(kind,`${title.slice(0,-1)} ACCESS`,`${item.name} requested temporary access through Portal Center.`,{deviceId:item.id,deviceName:item.name,deviceClass:key})}>REQUEST ACCESS</button>}</article>)}{status&&!status.hardware[key].length&&<p>NO {title} REPORTED BY AN AVAILABLE PLATFORM ADAPTER.</p>}</div></section>)}</div>}
    {mode==="diagnostics"&&<div className="diagnostics-grid"><section><header><span><small>ACTIVE ROUTE ANALYSIS</small><b>CONNECTION DIAGNOSTICS</b></span><button disabled={Boolean(busy)} onClick={()=>void localAction({operation:"diagnostics"},"Diagnostics completed")}>{busy==="diagnostics"?"TESTING…":"RUN DIAGNOSTICS"}</button></header><div><article><small>GATEWAY</small><b>{status?.diagnostics.gateway||"NOT TESTED"}</b></article><article><small>NAME SERVICE</small><b>{status?.diagnostics.dns||"NOT TESTED"}</b></article><article><small>INTERNET</small><b>{status?.diagnostics.internet||"NOT TESTED"}</b></article><article><small>LATENCY</small><b>{status?.diagnostics.latencyMs==null?"NOT REPORTED":`${status.diagnostics.latencyMs} MS`}</b></article></div><p>{status?.diagnostics.detail}</p></section><section className="removable-policy"><header><span><small>LCARS MOUNT CONTROLS</small><b>REMOVABLE DEVICE POLICY</b></span><em>{status?.policy.removable.toUpperCase()}</em></header><p>This policy governs LCARS mount controls. It does not claim to replace operating-system device security.</p><nav>{(["ask","allow","block"] as const).map(policy=><button className={status?.policy.removable===policy?"active":""} disabled={Boolean(busy)} key={policy} onClick={()=>void localAction({operation:"set-removable-policy",policy,confirmed:true},"Removable policy changed")}>{policy.toUpperCase()}</button>)}</nav></section><section className="firewall-status"><header><span><small>READ-ONLY PLATFORM STATUS</small><b>{status?.connections.firewall.provider||"FIREWALL"}</b></span><em>{status?.connections.firewall.active?"ACTIVE":"NOT ACTIVE"}</em></header><p>{status?.connections.firewall.detail}</p><div>{status?.connections.firewall.profiles.map(profile=><span key={profile}>{profile}</span>)}</div></section></div>}
  </section>;
}
