"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Mode="discover"|"updates"|"sources"|"history";
type Manager={id:string;name:string;sourceControl:boolean;cancellation:boolean;signaturePolicy:string};
type PackageRow={id:string;name:string;summary?:string;manager:string;current?:string;available?:string};
type Source={manager:string;id:string;name:string;url:string;enabled:boolean;mutable:boolean};
type History={id:string;status:string;action:string;manager:string;package:string;started:number;finished?:number;restartRequired?:boolean;rollbackGuidance?:string};
type Status={available:boolean;detail:string;managers:Manager[];updates:PackageRow[];count:number;sources:Source[];history:History[]};
type Details={id:string;name:string;manager:string;installed:boolean;currentVersion:string;availableVersion:string;summary:string;license:string;homepage:string;source:string;downloadSize:number|null;signaturePolicy:string;raw:string};
type Plan={token:string;action:"install"|"remove"|"update";manager:string;package:string;name:string;ready:boolean;previewAvailable:boolean|null;preview:string;storageImpact:number|null;restartRequired:boolean;restartAssessment:string;signaturePolicy:string;authorization:string;cancellable:boolean};
type Job={id:string;status:string;progress:number;log:string;action:string;manager:string;package:string;cancellable:boolean;restartRequired:boolean};

const CORE="http://127.0.0.1:8765";
const humanSize=(value:number|null)=>value==null?"NOT REPORTED":value>=1073741824?`${(value/1073741824).toFixed(1)} GB`:value>=1048576?`${(value/1048576).toFixed(1)} MB`:`${Math.ceil(value/1024)} KB`;
const stamp=(seconds:number)=>seconds?new Date(seconds*1000).toLocaleString():"PENDING";

export function SoftwareLogistics({notify}:{notify:(text:string,kind?:"info"|"error")=>void}){
  const [mode,setMode]=useState<Mode>("discover"),[status,setStatus]=useState<Status|null>(null),[query,setQuery]=useState(""),[manager,setManager]=useState(""),[results,setResults]=useState<PackageRow[]>([]),[details,setDetails]=useState<Details|null>(null),[plan,setPlan]=useState<Plan|null>(null),[job,setJob]=useState<Job|null>(null),[busy,setBusy]=useState(""),[error,setError]=useState(""),[sourceName,setSourceName]=useState(""),[sourceUrl,setSourceUrl]=useState(""),[sourceArmed,setSourceArmed]=useState("");
  const request=useCallback(async(path:string,options?:RequestInit)=>{const response=await fetch(CORE+path,options),value=await response.json();if(!response.ok||value.ok===false||value.error)throw new Error(value.error||"Local Core request failed");return value;},[]);
  const refresh=useCallback(async(scan=false)=>{setBusy("inventory");setError("");try{const value=await request(`/api/software-logistics${scan?"?refresh=1":""}`);setStatus(value);if(!manager&&value.managers?.length)setManager(value.managers[0].id);}catch(caught){setError(caught instanceof Error?caught.message:"Local Core is unavailable");}finally{setBusy("");}},[manager,request]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(false),0);return()=>window.clearTimeout(timer);},[refresh]);
  useEffect(()=>{if(!job||!["queued","running"].includes(job.status))return;const timer=window.setInterval(async()=>{try{const value=await request(`/api/software-logistics?operation=job&id=${encodeURIComponent(job.id)}`);setJob(value.job);if(!["queued","running"].includes(value.job.status)){void refresh(true);notify(value.job.status==="completed"?"Software transaction completed":"Software transaction did not complete",value.job.status==="completed"?"info":"error");}}catch(caught){setError(caught instanceof Error?caught.message:"Transaction status unavailable");}},700);return()=>window.clearInterval(timer);},[job,notify,refresh,request]);
  const search=async(event?:FormEvent)=>{event?.preventDefault();setBusy("search");setError("");setDetails(null);setPlan(null);try{const value=await request(`/api/software-logistics?operation=search&q=${encodeURIComponent(query)}${manager?`&manager=${encodeURIComponent(manager)}`:""}`);setResults(value.results||[]);}catch(caught){setError(caught instanceof Error?caught.message:"Search failed");}finally{setBusy("");}};
  const inspect=async(row:PackageRow)=>{setBusy(`details:${row.id}`);setError("");setPlan(null);try{setDetails(await request(`/api/software-logistics?operation=details&manager=${encodeURIComponent(row.manager)}&id=${encodeURIComponent(row.id)}`));}catch(caught){setError(caught instanceof Error?caught.message:"Package details unavailable");}finally{setBusy("");}};
  const review=async(action:Plan["action"])=>{if(!details)return;setBusy(`plan:${action}`);setError("");try{const value=await request(`/api/software-logistics?operation=plan&action=${action}&manager=${encodeURIComponent(details.manager)}&id=${encodeURIComponent(details.id)}`);setPlan(value.plan);}catch(caught){setError(caught instanceof Error?caught.message:"Change preview unavailable");}finally{setBusy("");}};
  const transact=async()=>{if(!plan)return;setBusy("transaction");setError("");try{const value=await request("/api/software-logistics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"start",token:plan.token,confirmed:true})});setJob(value.job);setPlan(null);if(value.job.status==="completed"){void refresh(true);notify(`${plan.name} ${plan.action} completed`);}else notify(`${plan.name} ${plan.action} started`);}catch(caught){const message=caught instanceof Error?caught.message:"Transaction was rejected";setError(message);notify(message,"error");}finally{setBusy("");}};
  const cancel=async()=>{if(!job)return;try{const value=await request("/api/software-logistics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"cancel",id:job.id})});setJob(value.job);notify("Software transaction cancelled");}catch(caught){notify(caught instanceof Error?caught.message:"Cancellation was rejected","error");}};
  const changeSource=async(action:"add"|"remove",source?:Source)=>{const name=source?.name||sourceName,sourceManager=source?.manager||(status?.managers.find(item=>item.id===manager)?.sourceControl?manager:status?.managers.find(item=>item.sourceControl)?.id||""),url=source?.url||sourceUrl,key=`${action}:${sourceManager}:${name}`;if(sourceArmed!==key){setSourceArmed(key);notify(`Press ${action.toUpperCase()} again to confirm source change`);return;}setBusy("source");setError("");try{const value=await request("/api/software-logistics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"source",action,manager:sourceManager,name,url,confirmed:true})});setJob(value.job);setSourceArmed("");setSourceName("");setSourceUrl("");notify("Software source change started");}catch(caught){const message=caught instanceof Error?caught.message:"Source change was rejected";setError(message);notify(message,"error");}finally{setBusy("");}};
  const currentManager=status?.managers.find(item=>item.id===manager),active=["queued","running"].includes(job?.status||"");
  return <section className="software-logistics">
    <header className="software-command-header"><span><small>VERSION 31.4 · CAPABILITY-AWARE PACKAGE CONTROL</small><b>SOFTWARE LOGISTICS</b><em>{status?.detail||"AWAITING LOCAL CORE"}</em></span><strong>{String(status?.count||0).padStart(2,"0")} UPDATES</strong></header>
    <nav className="software-modes" aria-label="Software Logistics sections">{(["discover","updates","sources","history"] as Mode[]).map((item,index)=><button type="button" className={mode===item?"active":""} aria-current={mode===item?"page":undefined} onClick={()=>{setMode(item);setPlan(null);}} key={item}><i>{String(index+1).padStart(2,"0")}</i><span>{item.toUpperCase()}</span></button>)}<button type="button" className="software-inventory-command" disabled={Boolean(busy)} onClick={()=>void refresh(true)}>{busy==="inventory"?"SCANNING…":"SCAN INVENTORY"}</button></nav>
    {error&&<p className="software-error">● {error}</p>}
    {!status?.available&&!error&&<p className="software-empty">NO SUPPORTED PACKAGE MANAGER WAS DETECTED ON THIS STATION.</p>}
    {mode==="discover"&&<div className="software-workspace">
      <section className="software-catalog"><form onSubmit={search}><select aria-label="Package manager" disabled={!status?.managers.length} value={manager} onChange={event=>setManager(event.target.value)}>{status?.managers.length?status.managers.map(item=><option value={item.id} key={item.id}>{item.name}</option>):<option value="">NO MANAGER</option>}</select><input aria-label="Search software" value={query} onChange={event=>setQuery(event.target.value)} placeholder="SEARCH AVAILABLE SOFTWARE…"/><button disabled={!status?.available||busy==="search"||query.trim().length<2}>{busy==="search"?"SEARCHING…":"SEARCH"}</button></form><div className="software-list">{results.map((row,index)=><button className={details?.id===row.id&&details.manager===row.manager?"active":""} onClick={()=>void inspect(row)} key={`${row.manager}:${row.id}`}><i>{String(index+1).padStart(2,"0")}</i><span><b>{row.name}</b><small>{row.summary||row.id}</small></span><em>{row.manager.toUpperCase()}</em></button>)}{!results.length&&<p>SEARCH THE ACTIVE PACKAGE CATALOG. RESULTS COME DIRECTLY FROM THE INSTALLED MANAGER.</p>}</div></section>
      <PackageInspector details={details} plan={plan} busy={busy} job={job} review={review} transact={transact} cancel={cancel}/>
    </div>}
    {mode==="updates"&&<div className="software-workspace"><section className="software-catalog"><div className="software-list">{status?.updates.map((row,index)=><button onClick={()=>void inspect(row)} key={`${row.manager}:${row.id}:${index}`}><i>{String(index+1).padStart(2,"0")}</i><span><b>{row.name}</b><small>{row.current} → {row.available}</small></span><em>{row.manager.toUpperCase()}</em></button>)}{status&&!status.updates.length&&<p>NO UPDATES REPORTED. SELECT SCAN INVENTORY FOR A LIVE CHECK.</p>}</div></section><PackageInspector details={details} plan={plan} busy={busy} job={job} review={review} transact={transact} cancel={cancel}/></div>}
    {mode==="sources"&&<div className="software-sources"><section><header><b>VERIFIED SOURCES</b><small>SYSTEM SOURCES ARE READ-ONLY. USER FLATPAK AND CUSTOM WINGET SOURCES CAN BE MANAGED HERE.</small></header>{status?.sources.map(source=><article key={`${source.manager}:${source.id}`}><span><b>{source.name}</b><small>{source.manager.toUpperCase()} · {source.url||"SYSTEM CONFIGURATION"}</small></span><em>{source.enabled?"ACTIVE":"DISABLED"}</em>{source.mutable&&<button className={sourceArmed===`remove:${source.manager}:${source.name}`?"armed":""} onClick={()=>void changeSource("remove",source)}>{sourceArmed===`remove:${source.manager}:${source.name}`?"CONFIRM REMOVE":"REMOVE"}</button>}</article>)}</section>{status?.managers.some(item=>item.sourceControl)&&<form onSubmit={event=>{event.preventDefault();void changeSource("add");}}><label>SOURCE MANAGER<select value={currentManager?.sourceControl?manager:status.managers.find(item=>item.sourceControl)?.id||""} onChange={event=>{setManager(event.target.value);setSourceArmed("");}}>{status.managers.filter(item=>item.sourceControl).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>SOURCE NAME<input value={sourceName} onChange={event=>{setSourceName(event.target.value);setSourceArmed("");}} placeholder="SOURCE-ID"/></label><label>HTTPS SOURCE ADDRESS<input value={sourceUrl} onChange={event=>{setSourceUrl(event.target.value);setSourceArmed("");}} placeholder="https://…"/></label><button className={sourceArmed===`add:${manager}:${sourceName}`?"armed":""}>{sourceArmed===`add:${manager}:${sourceName}`?"CONFIRM ADD":"ADD SOURCE"}</button></form>}</div>}
    {mode==="history"&&<div className="software-history">{status?.history.map((item,index)=><article key={`${item.id}:${index}`}><i>{item.status==="completed"?"✓":"!"}</i><span><b>{item.action?.toUpperCase()} · {item.package}</b><small>{item.manager?.toUpperCase()} · {stamp(item.finished||item.started)} · {item.status?.toUpperCase()}</small><em>{item.rollbackGuidance}</em></span>{item.restartRequired&&<strong>RESTART POSSIBLE</strong>}</article>)}{status&&!status.history.length&&<p>NO SOFTWARE TRANSACTIONS HAVE BEEN RECORDED.</p>}</div>}
    {active&&<aside className="software-job"><header><b>{job?.action?.toUpperCase()} · {job?.package}</b><em>{job?.status?.toUpperCase()} · {job?.progress||0}%</em></header><progress value={job?.progress||0} max="100"/><pre>{job?.log||"TRANSACTION QUEUED…"}</pre>{job?.cancellable&&<button onClick={()=>void cancel()}>CANCEL SAFE TRANSACTION</button>}</aside>}
  </section>;
}

function PackageInspector({details,plan,busy,job,review,transact,cancel}:{details:Details|null;plan:Plan|null;busy:string;job:Job|null;review:(action:Plan["action"])=>Promise<void>;transact:()=>Promise<void>;cancel:()=>Promise<void>}){
  if(!details)return <aside className="software-inspector empty"><b>PACKAGE INSPECTOR</b><p>SELECT A PACKAGE TO REVIEW ITS SOURCE, VERSION, SIZE, SIGNATURE POLICY, AND AVAILABLE ACTIONS.</p></aside>;
  return <aside className="software-inspector"><header><span><small>{details.manager.toUpperCase()} PACKAGE</small><b>{details.name}</b><em>{details.id}</em></span><strong>{details.installed?"INSTALLED":"AVAILABLE"}</strong></header><p>{details.summary}</p><dl><div><dt>CURRENT</dt><dd>{details.currentVersion||"NOT INSTALLED"}</dd></div><div><dt>AVAILABLE</dt><dd>{details.availableVersion||"MANAGER DEFAULT"}</dd></div><div><dt>DOWNLOAD</dt><dd>{humanSize(details.downloadSize)}</dd></div><div><dt>LICENSE</dt><dd>{details.license||"NOT REPORTED"}</dd></div><div><dt>SOURCE</dt><dd>{details.source||"MANAGER DEFAULT"}</dd></div></dl><p className="software-signature">✓ {details.signaturePolicy}</p><nav>{!details.installed&&<button disabled={Boolean(busy)} onClick={()=>void review("install")}>REVIEW INSTALL</button>}{details.installed&&<button disabled={Boolean(busy)} onClick={()=>void review("update")}>REVIEW UPDATE</button>}{details.installed&&<button disabled={Boolean(busy)} onClick={()=>void review("remove")}>REVIEW REMOVE</button>}</nav>{plan&&<section className="software-plan"><header><b>CHANGE PREVIEW · {plan.action.toUpperCase()}</b><em>{plan.authorization}</em></header><div><span><small>STORAGE IMPACT</small><b>{humanSize(plan.storageImpact)}</b></span><span><small>RESTART</small><b>{plan.restartAssessment}</b></span><span><small>CANCELLATION</small><b>{plan.cancellable?"SUPPORTED":"NOT SAFE"}</b></span></div><pre>{plan.preview}</pre><p>{plan.signaturePolicy}</p><button disabled={!plan.ready||Boolean(busy)} onClick={()=>void transact()}>{plan.ready?"CONFIRM AND START":"TRANSACTION BLOCKED"}</button></section>}{job&&!["queued","running"].includes(job.status)&&<p className={job.status==="completed"?"software-done":"software-error"}>{job.status.toUpperCase()} · {job.restartRequired?"RESTART MAY BE REQUIRED":"NO RESTART INDICATED"}{job.cancellable&&job.status==="running"&&<button onClick={()=>void cancel()}>CANCEL</button>}</p>}</aside>;
}
