"use client";

import { useCallback, useEffect, useRef, useState } from "react";

type UtilityMode="overview"|"clipboard"|"capture"|"printing";
type ClipboardEntry={id:string;text:string;createdAt:number;pinned:boolean};
type Printer={id:string;name:string;state:string;default?:boolean};
type PrintJob={id:string;printer:string;name:string;owner:string;state:string;size:number;submitted:string};
type UtilityStatus={ok:boolean;version:string;platform:string;capabilities:Record<string,boolean>;clipboard:{historyEnabled:boolean;privateMode:boolean;limit:number;history:ClipboardEntry[]};capture:{imageDirectory:string;videoDirectory:string;limitBytes:number};printing:{printers:Printer[];jobs:PrintJob[]}};
type PendingPrint={id:string;target:string};

const CORE="http://127.0.0.1:8765";
const dataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(blob);});
const formatBytes=(value=0)=>value>=1048576?`${(value/1048576).toFixed(1)} MB`:value>=1024?`${Math.round(value/1024)} KB`:`${value} B`;

export function DailyUtilities({bridge,doNotDisturb,toggleDnd,notify,open}:{bridge:boolean;doNotDisturb:boolean;toggleDnd:()=>void;notify:(text:string,kind?:"info"|"error")=>void;open:(target:"calendar"|"communications"|"search"|"operations"|"files"|"portals"|"settings")=>void}){
  const [mode,setMode]=useState<UtilityMode>("overview"),[status,setStatus]=useState<UtilityStatus|null>(null),[busy,setBusy]=useState(""),[error,setError]=useState(""),[recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0),[pendingPrint,setPendingPrint]=useState<PendingPrint|null>(null);
  const recordingRef=useRef<{stream:MediaStream;recorder:MediaRecorder;chunks:Blob[];started:number;timer:number}|null>(null);
  const request=useCallback(async(path:string,options?:RequestInit)=>{const response=await fetch(CORE+path,options),value=await response.json();if(!response.ok||value.ok===false||value.error)throw new Error(value.error||"Local Core request failed");return value;},[]);
  const refresh=useCallback(async()=>{if(!bridge)return;setBusy("refresh");setError("");try{setStatus(await request("/api/daily-utilities"));}catch(caught){setError(caught instanceof Error?caught.message:"Daily Utilities are unavailable");}finally{setBusy("");}},[bridge,request]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer);},[refresh]);
  useEffect(()=>()=>{const active=recordingRef.current;if(active){window.clearInterval(active.timer);if(active.recorder.state!=="inactive")active.recorder.stop();active.stream.getTracks().forEach(track=>track.stop());recordingRef.current=null;}},[]);
  const post=async(body:Record<string,unknown>)=>request("/api/daily-utilities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
  const run=async(body:Record<string,unknown>,message="Utility command completed")=>{setBusy(String(body.operation||"utility"));setError("");try{const result=await post(body);if(result.status)setStatus(result.status);else if(result.version)setStatus(result);notify(result.message||message);return result;}catch(caught){const value=caught instanceof Error?caught.message:"Utility command failed";setError(value);notify(value,"error");}finally{setBusy("");}};
  const setClipboardPolicy=async(changes:Record<string,unknown>)=>{const value=await run({operation:"policy",...changes},"Clipboard privacy policy updated");if(value?.version)setStatus(value);};
  const saveCapture=async(kind:"screenshot"|"recording",blob:Blob)=>{setBusy("save-capture");try{const result=await post({operation:"save-capture",kind,data:await dataUrl(blob)});notify(`${result.message} · ${result.path}`);}catch(caught){const value=caught instanceof Error?caught.message:"Capture could not be saved";setError(value);notify(value,"error");}finally{setBusy("");}};
  const screenshot=async()=>{setBusy("screenshot");setError("");let stream:MediaStream|undefined;try{
    if(!navigator.mediaDevices?.getDisplayMedia)throw new Error("Screen capture is unavailable in this environment");
    stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const video=document.createElement("video");video.srcObject=stream;video.muted=true;await video.play();
    if(!video.videoWidth||!video.videoHeight)await new Promise<void>((resolve)=>{video.onloadedmetadata=()=>resolve();});
    const canvas=document.createElement("canvas");canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d")?.drawImage(video,0,0);
    const blob=await new Promise<Blob|null>((resolve)=>canvas.toBlob(resolve,"image/png"));if(!blob)throw new Error("Screenshot encoding failed");await saveCapture("screenshot",blob);
  }catch(caught){const value=caught instanceof Error?caught.message:"Screenshot was cancelled";setError(value);notify(value,"error");}finally{stream?.getTracks().forEach(track=>track.stop());setBusy("");}};
  const stopRecording=()=>{const active=recordingRef.current;if(!active)return;if(active.recorder.state!=="inactive")active.recorder.stop();};
  const startRecording=async()=>{setBusy("recording");setError("");try{
    if(!navigator.mediaDevices?.getDisplayMedia||typeof MediaRecorder==="undefined")throw new Error("Screen recording is unavailable in this environment");
    const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}),mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm",recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:4_000_000}),chunks:Blob[]=[];
    const timer=window.setInterval(()=>{const active=recordingRef.current;if(active){setElapsed(Math.floor((Date.now()-active.started)/1000));if(Date.now()-active.started>=300000)stopRecording();}},500);
    recordingRef.current={stream,recorder,chunks,started:Date.now(),timer};setElapsed(0);setRecording(true);
    recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=()=>{window.clearInterval(timer);stream.getTracks().forEach(track=>track.stop());recordingRef.current=null;setRecording(false);void saveCapture("recording",new Blob(chunks,{type:"video/webm"}));};stream.getVideoTracks()[0]?.addEventListener("ended",stopRecording,{once:true});recorder.start(1000);notify("Screen recording started · five-minute safety limit active");
  }catch(caught){const value=caught instanceof Error?caught.message:"Screen recording was cancelled";setError(value);notify(value,"error");}finally{setBusy("");}};
  const cancelPrint=async(job:PrintJob)=>{const key=`lcars-print-approval:${job.id}`;setBusy(key);try{
    const stored=sessionStorage.getItem(key);if(stored){const result=await request(`/api/portal-request?id=${encodeURIComponent(stored)}`),approval=result.request;if(approval?.decision==="waiting"){setPendingPrint({id:stored,target:job.id});notify("Print cancellation is awaiting Portal approval");return;}if(approval?.decision==="approved"){const value=await post({operation:"execute",action:"cancel-print",target:job.id,approvalId:stored});sessionStorage.removeItem(key);setPendingPrint(null);setStatus(value.status);notify(value.message);return;}sessionStorage.removeItem(key);}
    const value=await post({operation:"request",action:"cancel-print",target:job.id});sessionStorage.setItem(key,value.request.id);setPendingPrint({id:value.request.id,target:job.id});notify("Print cancellation sent to Portal Center");
  }catch(caught){const value=caught instanceof Error?caught.message:"Print cancellation failed";setError(value);notify(value,"error");}finally{setBusy("");}};
  const cards:[UtilityMode,string,string][]=[["overview","01","OVERVIEW"],["clipboard","02","CLIPBOARD"],["capture","03","CAPTURE"],["printing","04","PRINTING"]];
  return <section className="daily-utilities">
    <header className="utility-command-header"><span><small>VERSION 31.5 · LOCAL-FIRST DAILY OPERATIONS</small><b>LCARS UTILITY COMMAND</b><em>{bridge?`${status?.platform?.toUpperCase()||"LOCAL CORE"} · CAPABILITY-AWARE`:"LOCAL CORE OFFLINE"}</em></span><strong>{recording?`REC ${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`:`${status?.printing.jobs.length||0} JOBS`}</strong></header>
    <nav className="utility-modes" aria-label="Daily Utilities sections">{cards.map(([id,code,label])=><button className={mode===id?"active":""} aria-current={mode===id?"page":undefined} key={id} onClick={()=>setMode(id)}><i>{code}</i><span>{label}</span></button>)}<button disabled={Boolean(busy)||!bridge} onClick={()=>void refresh()}>{busy==="refresh"?"SCANNING…":"REFRESH UTILITIES"}</button></nav>
    {error&&<p className="utility-error">● {error}</p>}
    {pendingPrint&&<aside className="utility-approval"><span><small>PORTAL AUTHORIZATION REQUIRED</small><b>CANCEL PRINT JOB {pendingPrint.target}</b><em>Approve the request, return here, then select the job’s cancellation control again.</em></span><button onClick={()=>open("portals")}>OPEN PORTAL CENTER</button></aside>}
    {mode==="overview"&&<div className="utility-overview">
      <article><i>01</i><span><small>CLIPBOARD PRIVACY</small><b>{status?.clipboard.privateMode?"PRIVATE MODE":status?.clipboard.historyEnabled?"HISTORY ACTIVE":"READ ON REQUEST"}</b><em>{status?.clipboard.history.length||0} SAVED · LOCAL ONLY</em></span><button onClick={()=>setMode("clipboard")}>MANAGE</button></article>
      <article><i>02</i><span><small>DISPLAY CAPTURE</small><b>{recording?"RECORDING":"READY"}</b><em>PORTAL-APPROVED · SAVED LOCALLY</em></span><button onClick={()=>setMode("capture")}>OPEN</button></article>
      <article><i>03</i><span><small>COMMUNICATIONS ROUTING</small><b>{doNotDisturb?"DO NOT DISTURB":"NOTICES ACTIVE"}</b><em>PORTAL NOTIFICATIONS → LCARS COMMS</em></span><button onClick={toggleDnd}>{doNotDisturb?"RESTORE":"DND"}</button></article>
      <article><i>04</i><span><small>PRINT MANAGEMENT</small><b>{status?.printing.jobs.length||0} QUEUED</b><em>{status?.printing.printers.length||0} PRINTERS REPORTED</em></span><button onClick={()=>setMode("printing")}>MANAGE</button></article>
      <section className="utility-integrations"><header><span><small>SHARED LCARS SERVICES</small><b>ONE ENVIRONMENT · NO DUPLICATE APPS</b></span></header><div><button onClick={()=>open("calendar")}>CALENDAR</button><button onClick={()=>open("communications")}>COMMUNICATIONS</button><button onClick={()=>open("search")}>UNIVERSAL SEARCH</button><button onClick={()=>open("operations")}>OPERATIONS LOG</button><button onClick={()=>open("files")}>FILES + DOCUMENTS</button><button onClick={()=>open("settings")}>UTILITY SETTINGS</button></div></section>
    </div>}
    {mode==="clipboard"&&<div className="utility-clipboard">
      <header><span><small>SENSITIVE LOCAL DATA</small><b>CLIPBOARD HISTORY</b><em>History is opt-in and never enters diagnostics, Search, or Federation automatically.</em></span><nav><button className={status?.clipboard.historyEnabled?"active":""} disabled={!status?.capabilities.clipboardRead||Boolean(busy)} onClick={()=>void setClipboardPolicy({historyEnabled:!status?.clipboard.historyEnabled})}>HISTORY {status?.clipboard.historyEnabled?"ON":"OFF"}</button><button className={status?.clipboard.privateMode?"private":""} onClick={()=>void setClipboardPolicy({privateMode:!status?.clipboard.privateMode})}>PRIVATE {status?.clipboard.privateMode?"ON":"OFF"}</button><button disabled={!status?.capabilities.clipboardRead||Boolean(busy)} onClick={()=>void run({operation:"clipboard-read"},status?.clipboard.historyEnabled?"Clipboard captured to local history":"Clipboard read once without storage")}>CAPTURE CURRENT</button><button disabled={!status?.clipboard.history.length||Boolean(busy)} onClick={()=>void run({operation:"clipboard-clear"},"Clipboard history cleared")}>CLEAR ALL</button></nav></header>
      <div>{status?.clipboard.history.map((item,index)=><article key={item.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{item.text.replace(/\s+/g," ").slice(0,120)}</b><small>{new Date(item.createdAt).toLocaleString()} · {item.text.length} CHARACTERS {item.pinned?"· PINNED":""}</small></span><button disabled={!status.capabilities.clipboardWrite||Boolean(busy)} onClick={()=>void run({operation:"clipboard-write",id:item.id},"Clipboard entry restored")}>RESTORE</button><button onClick={()=>void run({operation:"clipboard-pin",id:item.id},item.pinned?"Clipboard entry unpinned":"Clipboard entry pinned")}>{item.pinned?"UNPIN":"PIN"}</button><button onClick={()=>void run({operation:"clipboard-delete",id:item.id},"Clipboard entry deleted")}>DELETE</button></article>)}{status&&!status.clipboard.history.length&&<p>{status.clipboard.privateMode?"PRIVATE MODE ACTIVE · STORED HISTORY WAS CLEARED":"NO CLIPBOARD HISTORY · ENABLE HISTORY OR USE CAPTURE CURRENT"}</p>}</div>
    </div>}
    {mode==="capture"&&<div className="utility-capture">
      <article><i>01</i><span><small>STILL IMAGE</small><b>SCREENSHOT</b><p>Captures one operator-approved display and saves a PNG directly to the LCARS Captures folder.</p><em>{status?.capture.imageDirectory||"PICTURES / LCARS CAPTURES"}</em></span><button disabled={Boolean(busy)||recording} onClick={()=>void screenshot()}>{busy==="screenshot"?"AWAITING APPROVAL…":"TAKE SCREENSHOT"}</button></article>
      <article className={recording?"recording":""}><i>02</i><span><small>MOTION CAPTURE</small><b>SCREEN RECORDING</b><p>Records an operator-approved display in WebM. Recording stops after five minutes or when the shared display ends.</p><em>{status?.capture.videoDirectory||"VIDEOS / LCARS CAPTURES"}</em></span><button disabled={Boolean(busy)&&busy!=="recording"} onClick={()=>recording?stopRecording():void startRecording()}>{recording?`STOP + SAVE ${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`:"START RECORDING"}</button></article>
      <aside><b>CAPTURE PRIVACY</b><span>LCARS requests screen access through Portal Center. No capture is uploaded, synchronized, or added to activity history. Platform-mandated capture consent may still appear.</span></aside>
    </div>}
    {mode==="printing"&&<div className="utility-printing">
      <section><header><span><small>AVAILABLE DESTINATIONS</small><b>PRINTERS</b></span><em>{status?.printing.printers.length||0} REPORTED</em></header><div>{status?.printing.printers.map((printer,index)=><article key={printer.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{printer.name}</b><small>{printer.default?"DEFAULT · ":""}{printer.state||"STATUS NOT REPORTED"}</small></span></article>)}{status&&!status.printing.printers.length&&<p>NO PRINTERS REPORTED BY AN AVAILABLE PLATFORM ADAPTER.</p>}</div><button onClick={()=>open("files")}>OPEN FILES + DOCUMENTS TO PRINT</button></section>
      <section><header><span><small>ACTIVE SPOOL</small><b>PRINT JOBS</b></span><em>{status?.printing.jobs.length||0} QUEUED</em></header><div>{status?.printing.jobs.map((job,index)=><article key={job.id}><i>{String(index+1).padStart(2,"0")}</i><span><b>{job.name||job.id}</b><small>{job.printer} · {job.owner||"LOCAL OPERATOR"} · {formatBytes(job.size)} · {job.state}</small></span><button disabled={!status.capabilities.printCancel||Boolean(busy)} onClick={()=>void cancelPrint(job)}>{pendingPrint?.target===job.id?"CHECK APPROVAL":"REQUEST CANCEL"}</button></article>)}{status&&!status.printing.jobs.length&&<p>PRINT QUEUE CLEAR.</p>}</div></section>
    </div>}
  </section>;
}
