const tokenKey="lcars-padd-token-v28",legacyTokenKey="lcars-padd-token-v27",mediaKey="lcars-padd-media-target-v28";
let token=localStorage.getItem(tokenKey)||localStorage.getItem(legacyTokenKey)||"",lastSignal="",mediaTarget=localStorage.getItem(mediaKey)||"";
if(token&&!localStorage.getItem(tokenKey))localStorage.setItem(tokenKey,token);
const $=id=>document.getElementById(id),pairing=$("pairing"),consolePanel=$("console"),pairMessage=$("pair-message"),consoleMessage=$("console-message");
const releaseBadge=document.querySelector("#more-view>header strong"),recoveryVersion=$("recovery-version");if(releaseBadge)releaseBadge.textContent="VERSION 30.4 DEVELOPMENT";if(recoveryVersion)recoveryVersion.textContent="STATION UNKNOWN · CLIENT VERSION 30.4";
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.error||"LCARS link rejected the request");return result;}
function showPaired(paired){pairing.hidden=paired;consolePanel.hidden=!paired;}
function message(text,error=false){consoleMessage.textContent=text||"";consoleMessage.className=error?"error":"";}
async function pair(event){event.preventDefault();pairMessage.textContent="PAIRING…";try{const result=await api("/api/padd/pair",{method:"POST",body:JSON.stringify({name:$("device-name").value,code:$("pair-code").value})});token=result.token;localStorage.setItem(tokenKey,token);pairMessage.textContent=result.message;showPaired(true);await refresh();}catch(error){pairMessage.textContent=error.message;pairMessage.className="error";}}
async function transmit(action,value){try{const result=await api("/api/padd/action",{method:"POST",body:JSON.stringify({action,value})});message(result.message);if(navigator.vibrate)navigator.vibrate(35);setTimeout(refresh,400);}catch(error){message(error.message,true);}}
function rows(items,empty,action,secondary=""){return items.length?items.map((item,index)=>`<article><button data-dynamic-action="${action}" data-dynamic-value="${escapeHtml(item.id)}"><i>${String(index+1).padStart(2,"0")}</i><span><b>${escapeHtml(item.name||item.title||item.text)}</b><small>${escapeHtml(item.detail||item.status||"")}</small></span><em>›</em></button>${secondary?`<button class="secondary" data-dynamic-action="${secondary}" data-dynamic-value="${escapeHtml(item.id)}">${secondary==="notice-archive"?"ARCHIVE":"ACTION"}</button>`:""}</article>`).join(""):`<p>${empty}</p>`;}
function mediaRows(items){return items.length?items.map((item,index)=>`<article><button class="${String(item.id)===mediaTarget?"selected-source":""}" data-media-target="${escapeHtml(item.id)}"><i>${String(index+1).padStart(2,"0")}</i><span><b>${escapeHtml(item.name||item.title||"MEDIA")}</b><small>${escapeHtml(item.detail||item.status||"READY")}</small></span><em>${String(item.id)===mediaTarget?"✓":"›"}</em></button></article>`).join(""):`<p>NO ACTIVE MEDIA SOURCES</p>`;}
function render(result){
  const state=result.state||{},device=result.device||{},caps=result.capabilities||{},approval=result.approvalRequired||{};
  const media=state.media||[],savedMedia=media.find(item=>String(item.id)===mediaTarget),preferredMedia=savedMedia||media.find(item=>String(item.status||"").toLowerCase()==="playing")||media[0];mediaTarget=preferredMedia?.id||"";if(mediaTarget)localStorage.setItem(mediaKey,mediaTarget);else localStorage.removeItem(mediaKey);
  $("role-label").textContent=(device.role||"paired").toUpperCase();$("command-role").textContent=(device.role||"paired").toUpperCase();$("current-page").textContent=(state.page||"overview").toUpperCase();$("last-update").textContent=state.updatedAt?new Date(state.updatedAt*1000).toLocaleTimeString():"STANDBY";$("volume-readout").textContent=`${state.volume||0}%`;$("volume-value").textContent=`${state.volume||0}%`;$("master-volume").value=state.volume||0;$("master-volume").disabled=!caps.volume;$("routine-count").textContent=`${(state.routines||[]).length} ROUTINES`;$("notice-count").textContent=`${(state.notices||[]).length} SIGNALS`;$("mute-state").textContent=state.muted?"MUTED":"LIVE";$("dnd-toggle").textContent=state.doNotDisturb?"DISABLE DO NOT DISTURB":"ENABLE DO NOT DISTURB";$("dnd-toggle").dataset.value=String(!state.doNotDisturb);
  $("meters").innerHTML=(state.meters||[]).map(item=>`<article><span><small>${escapeHtml(item.label||item.name)}</small><b>${escapeHtml(item.value)}${typeof item.value==="number"?"%":""}</b></span><i><em style="width:${Math.max(0,Math.min(100,Number(item.value)||0))}%"></em></i></article>`).join("");
  $("status-notices").innerHTML=rows(state.notices||[],"NO PRIORITY SIGNALS","notice-read","notice-archive");$("communications-notices").innerHTML=rows(state.notices||[],"NO ACTIVE COMMUNICATIONS","notice-read","notice-archive");$("players").innerHTML=mediaRows(media);$("routines").innerHTML=rows(state.routines||[],caps.routine?"NO ROUTINES SHARED":"COMMAND ROLE REQUIRED","routine");$("apps").innerHTML=rows(state.apps||[],caps.app?"NO APPLICATIONS SHARED":"COMMAND ROLE REQUIRED","app");$("workstations").innerHTML=rows(state.workstations||[],caps.workstation?"NO WORKSTATIONS SHARED":"COMMAND ROLE REQUIRED","workstation");$("quick-actions").innerHTML=rows(state.quickActions||[],caps.quick?"NO QUICK ACTIONS SHARED":"OPERATOR ROLE REQUIRED","quick");
  $("workstation-state").textContent=state.activeWorkstation?`ACTIVE · ${state.activeWorkstation}`:"NO ACTIVE WORKSTATION";
  const release=state.release||{};$("release-stable").textContent=`STABLE · ${release.stable||"UNKNOWN"}`;$("release-development").textContent=`DEVELOPMENT · ${release.development||"UNKNOWN"}`;
  const compatibility=result.compatibility||"unknown";$("compatibility-state").textContent=compatibility==="compatible"?"VERSIONS ALIGNED":compatibility.replaceAll("-"," ").toUpperCase();$("compatibility-state").classList.toggle("attention",compatibility!=="compatible"&&compatibility!=="unknown");$("recovery-version").textContent=`STATION ${result.stationVersion||"UNKNOWN"} · CLIENT VERSION 30.4`;
  const access=state.accessibility||{},rawScale=Number(access.fontScale)||100,scale=rawScale>2?rawScale:rawScale*100;document.documentElement.style.fontSize=`${Math.max(90,Math.min(135,scale))}%`;document.body.classList.toggle("high-contrast",Boolean(access.highContrast));document.body.classList.toggle("reduced-motion",Boolean(access.reducedMotion));document.body.classList.toggle("color-safe",Boolean(access.colorSafe));
  const selected=state.widgets||[];document.querySelectorAll("[data-widget]").forEach(button=>{button.classList.toggle("active",selected.includes(button.dataset.widget));button.textContent=`${selected.includes(button.dataset.widget)?"✓":"+"} ${button.dataset.label}`;});document.querySelectorAll("[data-widget-surface]").forEach(node=>node.hidden=!selected.includes(node.dataset.widgetSurface));if(document.querySelector(".view.active[hidden]"))switchTab("command");
  document.querySelectorAll("[data-action]").forEach(button=>button.disabled=!caps[button.dataset.action]||(button.dataset.action==="media"&&!mediaTarget));document.querySelectorAll("[data-approval]").forEach(node=>node.textContent=approval[node.dataset.approval]?"DESKTOP APPROVAL":"DIRECT");
  $("clipboard-request").disabled=!caps.clipboard;
  if(result.signal&&result.signal.id!==lastSignal)void receiveSignal(result.signal,device);
}
async function receiveSignal(signal,device){lastSignal=signal.id;const payload=signal.payload||{},type=signal.type||"identify";try{if(type==="page")switchTab(payload.page==="media"?"media":payload.page==="communications"?"communications":payload.page==="settings"||payload.page==="updates"?"more":"status");else if(type==="clipboard"){await navigator.clipboard.writeText(payload.text||"");}else if(type==="file"){const bytes=Uint8Array.from(atob(payload.content||""),character=>character.charCodeAt(0)),link=document.createElement("a");link.href=URL.createObjectURL(new Blob([bytes],{type:payload.mime||"application/octet-stream"}));link.download=payload.name||"lcars-transfer.bin";link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}if(navigator.vibrate)navigator.vibrate([120,70,120]);message(type==="identify"?"IDENTIFY SIGNAL RECEIVED · THIS IS "+(device.name||"PADD"):`FEDERATION ${type.toUpperCase()} RECEIVED`);await api("/api/padd/signal-ack",{method:"POST",body:JSON.stringify({id:signal.id})});}catch(error){message(`FEDERATION DELIVERY FAILED · ${error.message}`,true);}}
async function heartbeat(latency){try{let battery=-1;if(navigator.getBattery){const value=await navigator.getBattery();battery=Math.round(value.level*100);}const connection=navigator.connection||{};await api("/api/padd/heartbeat",{method:"POST",body:JSON.stringify({battery,network:connection.effectiveType||"browser",latencyMs:latency,version:"30.4.0-development-web"})});}catch{}}
async function refresh(){const started=performance.now();try{const result=await api("/api/padd/state");showPaired(true);render(result);message("");heartbeat(Math.round(performance.now()-started));}catch(error){if(/authorization/i.test(error.message)){token="";localStorage.removeItem(tokenKey);localStorage.removeItem(legacyTokenKey);showPaired(false);}message(error.message,true);}}
function switchTab(name){document.querySelectorAll("[data-tab]").forEach(button=>button.classList.toggle("active",button.dataset.tab===name));document.querySelectorAll(".view").forEach(view=>view.classList.toggle("active",view.id===`${name}-view`));}
async function saveWidgets(widget){const selected=[...document.querySelectorAll("[data-widget].active")].map(button=>button.dataset.widget),next=selected.includes(widget)?selected.filter(value=>value!==widget):[...selected,widget];try{await api("/api/padd/preferences",{method:"POST",body:JSON.stringify({widgets:next})});await refresh();}catch(error){message(error.message,true);}}
$("pair-form").addEventListener("submit",pair);$("refresh").addEventListener("click",refresh);$("unpair").addEventListener("click",()=>{token="";localStorage.removeItem(tokenKey);localStorage.removeItem(legacyTokenKey);showPaired(false);pairMessage.textContent="This PADD forgot its local token. Revoke it from LCARS Settings if the device is no longer trusted.";});
document.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;if(button.dataset.tab)switchTab(button.dataset.tab);else if(button.dataset.mediaTarget){mediaTarget=button.dataset.mediaTarget;localStorage.setItem(mediaKey,mediaTarget);refresh();message("MEDIA CONTROL TARGET SELECTED");}else if(button.dataset.widget)saveWidgets(button.dataset.widget);else if(button.dataset.action)transmit(button.dataset.action,button.dataset.action==="media"?{player:mediaTarget,command:button.dataset.value}:button.dataset.value);else if(button.dataset.dynamicAction&&button.dataset.dynamicAction!=="noop")transmit(button.dataset.dynamicAction,button.dataset.dynamicValue);});
$("master-volume").addEventListener("input",event=>$("volume-value").textContent=`${event.target.value}%`);$("master-volume").addEventListener("change",event=>transmit("volume",Number(event.target.value)));$("clipboard-request").addEventListener("click",()=>transmit("clipboard",$("clipboard-text").value));
$("retry-recovery").addEventListener("click",refresh);
api("/api/padd/status").then(status=>{$("link-state").textContent=status.enabled?"ONLINE":"STANDBY";if(token)refresh();else showPaired(false);}).catch(error=>{pairMessage.textContent=error.message;showPaired(false);});
setInterval(()=>token&&refresh(),1800);if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
