const tokenKey="lcars-padd-token-v27";
let token=localStorage.getItem(tokenKey)||"",latest=null;
const $=id=>document.getElementById(id),pairing=$("pairing"),consolePanel=$("console"),pairMessage=$("pair-message"),consoleMessage=$("console-message");
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.error||"LCARS link rejected the request");return result;}
function showPaired(paired){pairing.hidden=paired;consolePanel.hidden=!paired;}
function message(text,error=false){consoleMessage.textContent=text||"";consoleMessage.className=error?"error":"";}
async function pair(event){event.preventDefault();pairMessage.textContent="PAIRING…";try{const result=await api("/api/padd/pair",{method:"POST",body:JSON.stringify({name:$("device-name").value,code:$("pair-code").value})});token=result.token;localStorage.setItem(tokenKey,token);pairMessage.textContent=result.message;showPaired(true);await refresh();}catch(error){pairMessage.textContent=error.message;pairMessage.className="error";}}
async function transmit(action,value){try{const result=await api("/api/padd/action",{method:"POST",body:JSON.stringify({action,value})});message(result.message);setTimeout(refresh,400);}catch(error){message(error.message,true);}}
function renderList(target,items,empty,action){target.innerHTML=items.length?items.map((item,index)=>`<button data-dynamic-action="${action}" data-dynamic-value="${escapeHtml(item.id)}"><i>${String(index+1).padStart(2,"0")}</i><span><b>${escapeHtml(item.name||item.title||item.text)}</b><small>${escapeHtml(item.detail||item.status||"")}</small></span><em>›</em></button>`).join(""):`<p>${empty}</p>`;}
function render(result){latest=result;const state=result.state,device=result.device,caps=result.capabilities;$("role-label").textContent=device.role.toUpperCase();$("command-role").textContent=device.role.toUpperCase();$("current-page").textContent=(state.page||"overview").toUpperCase();$("last-update").textContent=state.updatedAt?new Date(state.updatedAt*1000).toLocaleTimeString():"STANDBY";$("volume-readout").textContent=`${state.volume}%`;$("volume-value").textContent=`${state.volume}%`;$("master-volume").value=state.volume;$("master-volume").disabled=!caps.volume;$("routine-count").textContent=`${state.routines.length} ROUTINES`;$("notice-count").textContent=`${state.notices.length} SIGNALS`;$("mute-state").textContent=state.muted?"MUTED":"LIVE";$("dnd-toggle").textContent=state.doNotDisturb?"DISABLE DO NOT DISTURB":"ENABLE DO NOT DISTURB";$("dnd-toggle").dataset.value=String(!state.doNotDisturb);$("meters").innerHTML=state.meters.map(item=>`<article><span><small>${escapeHtml(item.label||item.name)}</small><b>${escapeHtml(item.value)}${typeof item.value==="number"?"%":""}</b></span><i><em style="width:${Math.max(0,Math.min(100,Number(item.value)||0))}%"></em></i></article>`).join("");renderList($("notices"),state.notices,"NO PRIORITY SIGNALS","noop");renderList($("players"),state.media,"NO ACTIVE MEDIA SOURCES","noop");renderList($("routines"),state.routines,caps.routine?"NO ROUTINES SHARED":"COMMAND ROLE REQUIRED","routine");renderList($("apps"),state.apps,caps.app?"NO APPLICATIONS SHARED":"COMMAND ROLE REQUIRED","app");document.querySelectorAll("[data-action]").forEach(button=>button.disabled=!caps[button.dataset.action]);}
async function refresh(){try{const result=await api("/api/padd/state");showPaired(true);render(result);message("");}catch(error){if(/authorization/i.test(error.message)){token="";localStorage.removeItem(tokenKey);showPaired(false);}message(error.message,true);}}
function switchTab(name){document.querySelectorAll("[data-tab]").forEach(button=>button.classList.toggle("active",button.dataset.tab===name));document.querySelectorAll(".view").forEach(view=>view.classList.toggle("active",view.id===`${name}-view`));}
$("pair-form").addEventListener("submit",pair);$("refresh").addEventListener("click",refresh);$("unpair").addEventListener("click",()=>{token="";localStorage.removeItem(tokenKey);showPaired(false);pairMessage.textContent="This PADD forgot its local token. Revoke it from LCARS Settings if the device is no longer trusted.";});
document.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;if(button.dataset.tab)switchTab(button.dataset.tab);else if(button.dataset.action)transmit(button.dataset.action,button.dataset.value);else if(button.dataset.dynamicAction&&button.dataset.dynamicAction!=="noop")transmit(button.dataset.dynamicAction,button.dataset.dynamicValue);});
$("master-volume").addEventListener("input",event=>$("volume-value").textContent=`${event.target.value}%`);$("master-volume").addEventListener("change",event=>transmit("volume",Number(event.target.value)));
api("/api/padd/status").then(status=>{$("link-state").textContent=status.enabled?"ONLINE":"STANDBY";if(token)refresh();else showPaired(false);}).catch(error=>{pairMessage.textContent=error.message;showPaired(false);});
setInterval(()=>token&&refresh(),2500);if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
