const { app, BrowserWindow, protocol, net, shell, session, screen } = require("electron");
app.commandLine.appendSwitch("autoplay-policy", "no-user-gesture-required");
const { spawn } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const http = require("node:http");
protocol.registerSchemesAsPrivileged([{scheme:"lcars",privileges:{standard:true,secure:true,supportFetchAPI:true}}]);
let mainWindow=null,bridgeProcess=null,windows=new Set();
app.setName("LCARS Command Interface");
if(process.platform==="win32")app.setAppUserModelId("com.lcars.commandinterface");
if(process.platform==="linux")app.commandLine.appendSwitch("class","lcars-command-interface");
const root=()=>app.isPackaged?process.resourcesPath:path.resolve(__dirname,"..");
const bridge=()=>app.isPackaged?path.join(process.resourcesPath,"bridge",process.platform==="win32"?"lcars_bridge_windows.py":"lcars_bridge_linux.py"):path.join(root(),process.platform==="win32"?"windows/lcars_bridge_windows.py":"local/lcars_bridge.py");
const recovery=()=>app.isPackaged?path.join(process.resourcesPath,"recovery","lcars-recovery.sh"):path.join(root(),"local/lcars-recovery.sh");
function recover(){if(process.platform!=="linux"||!fs.existsSync(recovery()))return;try{const p=spawn("bash",[recovery()],{stdio:"ignore",detached:true,env:{...process.env,LCARS_RECOVERY_SILENT:"1"}});p.unref()}catch{}}
function startBridge(){let python="python3",args=[];if(process.platform==="win32"){python="py";args=["-3"]}bridgeProcess=spawn(python,[...args,bridge()],{cwd:root(),stdio:"ignore",windowsHide:true,env:{...process.env,LCARS_DESKTOP_APP:"1",LCARS_EXECUTABLE:process.env.APPIMAGE||process.execPath,LCARS_PARENT_PID:String(process.pid)}})}
function ready(attempts=80){return new Promise(resolve=>{const check=n=>{const req=http.get("http://127.0.0.1:8765/api/health-check",res=>{res.resume();resolve(true)});req.setTimeout(250,()=>req.destroy());req.on("error",()=>n<=0?resolve(false):setTimeout(()=>check(n-1),100))};check(attempts)})}
const startupAudioBootstrap=`(()=>{if(window.__lcarsPlayStartupSound)return;let audio=null,played=false;window.__lcarsPlayStartupSound=async(force=false)=>{try{if(played&&!force)return{ok:true,status:'ALREADY PLAYED'};const prefs=JSON.parse(localStorage.getItem('lcars-shell-prefs')||'{}');if(!force&&prefs.startupSound===false)return{ok:true,status:'DISABLED'};if(force&&audio){audio.pause();audio.currentTime=0}audio=new Audio(new URL('assets/sounds/power-up.mp3',window.location.href).href);audio.preload='auto';audio.volume=.42;await audio.play();played=true;const result={ok:true,status:'PLAYING',asset:audio.currentSrc,output:audio.sinkId||'SYSTEM DEFAULT'};window.dispatchEvent(new CustomEvent('lcars-startup-audio-result',{detail:result}));return result}catch(error){const result={ok:false,status:'FAILED',error:String(error),asset:new URL('assets/sounds/power-up.mp3',window.location.href).href,output:'SYSTEM DEFAULT'};window.dispatchEvent(new CustomEvent('lcars-startup-audio-result',{detail:result}));return result}}})()`;
function createWindow({terminal=false,display="",position=""}={}){const icon=app.isPackaged?path.join(process.resourcesPath,"icons",process.platform==="win32"?"lcars-command-interface.ico":"lcars-command-interface.png"):path.join(root(),"desktop/icons/512x512.png");const point=position.split(",").map(Number);const target=point.length===2&&point.every(Number.isFinite)?screen.getDisplayNearestPoint({x:point[0],y:point[1]}):screen.getAllDisplays().find(d=>d.label===display||d.id===Number(display));const options={title:terminal?"LCARS Remote Terminal":"LCARS Command Interface",backgroundColor:"#000",fullscreen:true,autoHideMenuBar:true,show:false,icon,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}};if(target)options.bounds=target.bounds;const win=new BrowserWindow(options);windows.add(win);if(!mainWindow)mainWindow=win;win.removeMenu();if(target)win.setBounds(target.bounds);win.webContents.on("did-finish-load",()=>win.webContents.executeJavaScript(startupAudioBootstrap).catch(()=>{}));win.once("ready-to-show",()=>{win.show();win.setFullScreen(true);if(!terminal)setTimeout(()=>win.webContents.executeJavaScript("window.__lcarsPlayStartupSound?.()").catch(()=>{}),450)});win.webContents.setWindowOpenHandler(({url})=>{if(url.startsWith("lcars://app/"))return{action:"allow",overrideBrowserWindowOptions:{title:"LCARS Detached Workspace",backgroundColor:"#000",autoHideMenuBar:true,width:1200,height:800,icon,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}}};if(/^https?:/i.test(url))shell.openExternal(url);return{action:"deny"}});win.webContents.on("will-navigate",(e,url)=>{if(!url.startsWith("lcars://app/"))e.preventDefault()});win.webContents.on("before-input-event",(e,input)=>{if(input.key==="F11"&&input.type==="keyDown"){win.setFullScreen(!win.isFullScreen());e.preventDefault()}});win.webContents.on("render-process-gone",recover);win.on("closed",()=>{windows.delete(win);if(win===mainWindow)mainWindow=windows.values().next().value||null});win.loadURL("lcars://app/index.html"+(terminal?"?section=terminal":""));return win}
function protocolHandler(){const dir=path.join(app.getAppPath(),"desktop-dist");protocol.handle("lcars",request=>{const url=new URL(request.url),requested=decodeURIComponent(url.pathname==="/"?"/index.html":url.pathname),resolved=path.resolve(dir,`.${requested}`),target=resolved.startsWith(dir)&&fs.existsSync(resolved)?resolved:path.join(dir,"index.html");return net.fetch(`file://${target}`)})}
const parseLaunch=args=>({terminal:args.includes("--lcars-terminal"),display:(args.find(x=>x.startsWith("--display="))||"").slice(10),position:(args.find(x=>x.startsWith("--position="))||"").slice(11)});const lock=app.requestSingleInstanceLock();if(!lock)app.quit();else{app.on("second-instance",(_event,argv)=>{const request=parseLaunch(argv);if(request.terminal)createWindow(request);else if(mainWindow){if(mainWindow.isMinimized())mainWindow.restore();mainWindow.focus()}});app.whenReady().then(async()=>{protocolHandler();await session.defaultSession.clearCache();recover();startBridge();await ready();createWindow(parseLaunch(process.argv))});app.on("before-quit",()=>{recover();if(bridgeProcess&&!bridgeProcess.killed)bridgeProcess.kill("SIGTERM")});app.on("window-all-closed",()=>app.quit())}
