const { app, BrowserWindow, protocol, net, shell, session, screen } = require("electron");
app.commandLine.appendSwitch("autoplay-policy", "no-user-gesture-required");
const { spawn, spawnSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const http = require("node:http");
protocol.registerSchemesAsPrivileged([{scheme:"lcars",privileges:{standard:true,secure:true,supportFetchAPI:true}}]);
let mainWindow=null,bridgeProcess=null,windows=new Set();
app.setName("LCARS Command Interface");
if(process.platform==="win32")app.setAppUserModelId("com.lcars.commandinterface");
if(process.platform==="linux")app.commandLine.appendSwitch("class","lcars-command-interface");
const root=()=>app.isPackaged?process.resourcesPath:path.resolve(__dirname,"..");
const bridge=()=>app.isPackaged?path.join(process.resourcesPath,"bridge",process.platform==="win32"?"lcars_bridge_windows.py":"lcars_bridge_linux.py"):path.join(root(),process.platform==="win32"?"windows/lcars_bridge_windows.py":"local/lcars_bridge.py");
const recovery=()=>app.isPackaged?path.join(process.resourcesPath,"recovery","lcars-recovery.sh"):path.join(root(),"local/lcars-recovery.sh");
function recover(){if(process.platform!=="linux"||!fs.existsSync(recovery()))return;try{const p=spawn("bash",[recovery()],{stdio:"ignore",detached:true,env:{...process.env,LCARS_RECOVERY_SILENT:"1"}});p.unref()}catch{}}
function windowsPythonCandidates(){const candidates=[["py",["-3"]],["python",[]],["python3",[]]];const localPrograms=process.env.LOCALAPPDATA?path.join(process.env.LOCALAPPDATA,"Programs","Python"):"";if(localPrograms&&fs.existsSync(localPrograms))try{for(const entry of fs.readdirSync(localPrograms).sort().reverse()){const exe=path.join(localPrograms,entry,"python.exe");if(fs.existsSync(exe))candidates.push([exe,[]])}}catch{}return candidates}
function resolveWindowsPython(){for(const [command,args] of windowsPythonCandidates()){try{const probe=spawnSync(command,[...args,"--version"],{stdio:"ignore",windowsHide:true,timeout:4000});if(!probe.error&&probe.status===0)return[command,args]}catch{}}return null}
function startBridge(){let python="python3",args=[];if(process.platform==="win32"){const resolved=resolveWindowsPython();if(!resolved){console.error("LCARS Windows bridge: no usable Python runtime was found.");return false}[python,args]=resolved}try{bridgeProcess=spawn(python,[...args,bridge()],{cwd:root(),stdio:"ignore",windowsHide:true,env:{...process.env,LCARS_DESKTOP_APP:"1",LCARS_EXECUTABLE:process.env.APPIMAGE||process.execPath,LCARS_PARENT_PID:String(process.pid)}});bridgeProcess.on("error",error=>console.error("LCARS bridge process failed to start:",error));return true}catch(error){console.error("LCARS bridge process could not be created:",error);bridgeProcess=null;return false}}
function ready(attempts=80){return new Promise(resolve=>{const check=n=>{const req=http.get("http://127.0.0.1:8765/api/health-check",res=>{res.resume();resolve(true)});req.setTimeout(250,()=>req.destroy());req.on("error",()=>n<=0?resolve(false):setTimeout(()=>check(n-1),100))};check(attempts)})}
function configurePermissions(){const lcarsOrigin=value=>{try{return new URL(value||"").protocol==="lcars:"}catch{return false}};session.defaultSession.setPermissionCheckHandler((_webContents,permission,requestingOrigin,details)=>permission==="media"&&lcarsOrigin(requestingOrigin||details?.requestingUrl));session.defaultSession.setPermissionRequestHandler((_webContents,permission,callback,details)=>callback(permission==="media"&&lcarsOrigin(details?.requestingUrl)))}
const startupAudioBootstrap=`(()=>{if(window.__lcarsPlayStartupSound)return;let audio=null,objectUrl='',played=false;window.__lcarsPlayStartupSound=async(force=false)=>{const asset=new URL('assets/sounds/power-up.mp3',window.location.href).href;try{if(played&&!force)return{ok:true,status:'ALREADY PLAYED'};const prefs=JSON.parse(localStorage.getItem('lcars-shell-prefs')||'{}');if(!force&&prefs.startupSound===false)return{ok:true,status:'DISABLED'};if(force&&audio){audio.pause();audio.currentTime=0}if(!audio){const response=await fetch(asset,{cache:'no-store'});if(!response.ok)throw new Error('Audio asset returned HTTP '+response.status);const blob=await response.blob();if(!blob.type.startsWith('audio/'))throw new Error('Audio asset returned '+(blob.type||'an unknown content type'));objectUrl=URL.createObjectURL(blob);audio=new Audio(objectUrl);audio.preload='auto';audio.volume=.42}await audio.play();played=true;const result={ok:true,status:'PLAYING',asset,output:audio.sinkId||'SYSTEM DEFAULT'};window.dispatchEvent(new CustomEvent('lcars-startup-audio-result',{detail:result}));return result}catch(error){const result={ok:false,status:'FAILED',error:String(error),asset,output:'SYSTEM DEFAULT'};window.dispatchEvent(new CustomEvent('lcars-startup-audio-result',{detail:result}));return result}};window.addEventListener('unload',()=>objectUrl&&URL.revokeObjectURL(objectUrl),{once:true})})()`;
function createWindow({terminal=false,display="",position="",safe=false,kiosk=false,lcarsSession=false}={}){const icon=app.isPackaged?path.join(process.resourcesPath,"icons",process.platform==="win32"?"lcars-command-interface.ico":"lcars-command-interface.png"):path.join(root(),"desktop/icons/512x512.png");const point=position.split(",").map(Number);const target=point.length===2&&point.every(Number.isFinite)?screen.getDisplayNearestPoint({x:point[0],y:point[1]}):screen.getAllDisplays().find(d=>d.label===display||d.id===Number(display));const options={title:terminal?"LCARS Remote Terminal":"LCARS Command Interface",backgroundColor:"#000",fullscreen:true,autoHideMenuBar:true,show:false,icon,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}};if(target)options.bounds=target.bounds;const win=new BrowserWindow(options);windows.add(win);if(!mainWindow)mainWindow=win;win.removeMenu();if(target)win.setBounds(target.bounds);win.webContents.on("did-finish-load",()=>win.webContents.executeJavaScript(startupAudioBootstrap).catch(()=>{}));win.once("ready-to-show",()=>{win.show();win.setFullScreen(true);if(!terminal)setTimeout(()=>win.webContents.executeJavaScript("window.__lcarsPlayStartupSound?.()").catch(()=>{}),450)});win.webContents.setWindowOpenHandler(({url})=>{if(url.startsWith("lcars://app/"))return{action:"allow",overrideBrowserWindowOptions:{title:"LCARS Detached Workspace",backgroundColor:"#000",autoHideMenuBar:true,width:1200,height:800,icon,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}}};if(/^https?:/i.test(url))shell.openExternal(url);return{action:"deny"}});win.webContents.on("will-navigate",(e,url)=>{if(!url.startsWith("lcars://app/"))e.preventDefault()});win.webContents.on("before-input-event",(e,input)=>{if(input.key==="F11"&&input.type==="keyDown"){win.setFullScreen(!win.isFullScreen());e.preventDefault()}});win.webContents.on("render-process-gone",recover);win.on("closed",()=>{windows.delete(win);if(win===mainWindow)mainWindow=windows.values().next().value||null});const query=new URLSearchParams();if(terminal)query.set("section","terminal");if(safe)query.set("safe","1");if(kiosk)query.set("kiosk","1");if(lcarsSession)query.set("lcars-session","1");win.loadURL("lcars://app/index.html"+(query.size?"?"+query.toString():""));return win}
const lcarsMime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".svg":"image/svg+xml",".ico":"image/x-icon",".mp3":"audio/mpeg",".wav":"audio/wav",".ogg":"audio/ogg",".woff":"font/woff",".woff2":"font/woff2"};
function protocolHandler(){const dir=path.join(app.getAppPath(),"desktop-dist");protocol.handle("lcars",request=>{const url=new URL(request.url),requested=decodeURIComponent(url.pathname==="/"?"/index.html":url.pathname),resolved=path.resolve(dir,`.${requested}`),relative=path.relative(dir,resolved),inside=relative&&!relative.startsWith("..")&&!path.isAbsolute(relative);let target=inside&&fs.existsSync(resolved)&&fs.statSync(resolved).isFile()?resolved:null;if(!target&&(!path.extname(requested)||path.extname(requested)===".html"))target=path.join(dir,"index.html");if(!target)return new Response("LCARS asset not found",{status:404,headers:{"Content-Type":"text/plain; charset=utf-8"}});return new Response(fs.readFileSync(target),{status:200,headers:{"Content-Type":lcarsMime[path.extname(target).toLowerCase()]||"application/octet-stream","Cache-Control":app.isPackaged?"public, max-age=31536000, immutable":"no-cache","Accept-Ranges":"bytes"}})})}
const parseLaunch=args=>({terminal:args.includes("--lcars-terminal"),safe:args.includes("--lcars-safe"),kiosk:args.includes("--lcars-kiosk"),lcarsSession:args.includes("--lcars-session"),display:(args.find(x=>x.startsWith("--display="))||"").slice(10),position:(args.find(x=>x.startsWith("--position="))||"").slice(11)});const lock=app.requestSingleInstanceLock();if(!lock)app.quit();else{app.on("second-instance",(_event,argv)=>{const request=parseLaunch(argv);if(request.terminal)createWindow(request);else if(mainWindow){if(mainWindow.isMinimized())mainWindow.restore();mainWindow.focus()}});app.whenReady().then(async()=>{protocolHandler();configurePermissions();await session.defaultSession.clearCache();recover();startBridge();await ready();const request=parseLaunch(process.argv);if(request.kiosk)fetch("http://127.0.0.1:8765/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"shell-mode-on"})}).catch(()=>{});createWindow(request)});app.on("before-quit",()=>{recover();if(bridgeProcess&&!bridgeProcess.killed)bridgeProcess.kill("SIGTERM")});app.on("window-all-closed",()=>app.quit())}
